### ISSUE TITLE
Retraining on previously

### ISSUE THREAD

**Issue by arsalan-ahmed-grotabyte** [ddangelov/Top2Vec#100]
I have a couple of questions. 

1. When we select BERT or USE,  then do you code perform fine tuning using those pre-trained models or just pass sentence through those model to get the embedding?
2. Once the model is trained then using that trained model file, is it possible to perform training again given an incremented dataset?

**Comment by ddangelov** [comment]
There is no fine tuning performed for BERT or USE at the moment. After creating an initial model you can add more data with the `add_documents` method.
