### ISSUE TITLE
OOM when applying UMAP to large document vectors

### ISSUE THREAD

**Issue by avouacr** [ddangelov/Top2Vec#101]
Hi,

First of all, thank's for the great paper and library.

I've been using Top2Vec with a pre-trained sentence-transformer. I'm doing the computations on a Google Colab instance to benefit from GPU paralellization when inferring the vectors. However, I systemically run into an out of memory error during the dimensionality reduction step. I don't get any error when using 300d Doc2Vec vectors, so it's likely related to the high dimension of transformers embeddings. As suggested in the [UMAP faq](https://umap-learn.readthedocs.io/en/latest/faq.html#i-ran-out-of-memory-help), adding the `low_memory=True` option when instantiating `umap.UMAP` solves the issue, at the expense of additional computation time. I think making this option accessible when instantiating `Top2Vec` would be useful.

**Comment by ddangelov** [comment]
Thank you for the suggestion.

**Comment by ddangelov** [comment]
Passing UMAP parameters to Top2Vec is now possible.
