### ISSUE TITLE
Bigrams and Trigrams

### ISSUE THREAD

**Issue by lppier** [ddangelov/Top2Vec#105]
Hi @ddangelov , great work here, appreciate it! 
Just wondering, would this support using bigrams and trigrams? So far the topic words that come up are unigrams from what I observe. 
Example: "carbon credits" is usually seen together, not separately as "carbon" and "credits". 
Thanks!

**Comment by ddangelov** [comment]
You can pass a custom tokenizer to the Top2Vec `tokenizer` parameter.

**Comment by lppier** [comment]
I c, thanks!

**Comment by Jeetkarsh** [comment]
Seems, it doesn't support tokenizer now.

**Comment by ddangelov** [comment]
> Seems, it doesn't support tokenizer now.

I am not sure what you mean. Top2Vec still allows to to pass your own tokenizer with the `tokenizer` parameter.
