### ISSUE TITLE
Can we use other pre-trained models from HuggingFace?

### ISSUE THREAD

**Issue by UmutAlihan** [ddangelov/Top2Vec#106]
I would love to use Top2Vec with a custom pretrained language model. Could you please guide me through to include [custom models ](https://huggingface.co/dbmdz/bert-base-turkish-128k-cased )into [acceptable_embedding_models of Top2Vec()](https://github.com/ddangelov/Top2Vec/blob/e67b2104cdadfdea58299343fa4f944c1f19908c/top2vec/Top2Vec.py#L222
) class?

Lastly, it is great pleasure to read such innovative and high quality contributions to the open source. Thank you very much and I appreciate your great efforts!

**Comment by ddangelov** [comment]
Currently only models that have been tested and are compatible are added. Perhaps a more generic way of passing models could be added in the future.
