### ISSUE TITLE
Can top2vec package handle keywords that has space??

### ISSUE THREAD

**Issue by Alisha1992** [ddangelov/Top2Vec#109]
Hi Dangelov,

Could you please help me understand if top2vec package be able handle keywords like "cocoa butter" as single word??  Eg. Cocoa butter is single ingredient name. I want to look for it in the dataset using keyword = "cocoa butter"
 
Your quick response will be of great help.

**Comment by ddangelov** [comment]
Currently you will need to pass them as `keywords=['cocao', 'butter']`. There will be a query feature coming where you can write free text queries but for now you must pass keywords as a list.
