### ISSUE TITLE
How to run top2vec in GPU

### ISSUE THREAD

**Issue by KVSAkhilesh** [ddangelov/Top2Vec#110]
Hi Team,
I am using top2vec for topic modelling and I am running in AWS EC2 Linux environment. It's GPU enables but model is running very slow. Could you please let me know how to run this model on GPU environment.
Thanks in advance

**Comment by ddangelov** [comment]
What parameters have you passed to the model?

If using `embedding_model` other than `doc2vec` then GPU could be utilized assuming either tensorflow or pytorch is installed correctly for GPU usage. This will depend on which `embedding_model` is used. UMAP will largely benefit from multiple cores.

**Comment by KVSAkhilesh** [comment]
Hi Dimo,

Please find the below two commands I have been used for the running the model and searching for the keyword in the model. 
Could you please let me know if I miss any thing on the code.

pos_mdl = Top2Vec(documents = pos_df['Improved_Text'], speed = "learn", workers=worker)
pos_topic_words, pos_word_scores, pos_topic_scores, pos_topic_nums_f1 = pos_mdl1.search_topics(keywords = [Input_Product], num_topics = Input_Topics)

**Comment by ddangelov** [comment]
You need to set `embedding_model` to something other than `doc2vec` for GPU usage. Otherwise if using the default which is `doc2vec` make sure `worker` specifies an appropriate number of cores and also set `use_corpus_file` to true.
