### ISSUE TITLE
Issue loading saved model

### ISSUE THREAD

**Issue by ErinKnochenhauer** [ddangelov/Top2Vec#111]
Hello! 

I have a successfully saved model that I am having trouble loading. 

I am getting an Attribute error:

`AttributeError                            Traceback (most recent call last)
 in 
----> 1 model = Top2Vec.load("./pickled_models/top2vec_model_1-6")

~/repos/legally_blurb/.venv/lib/python3.8/site-packages/top2vec/Top2Vec.py in load(cls, file)
    427 
    428         # load document index
--> 429         if top2vec_model.documents_indexed:
    430             if not _HAVE_HNSWLIB:
    431                 raise ImportError(f"Cannot load document index.\n\n"

AttributeError: 'Top2Vec' object has no attribute 'documents_indexed'`

I tried your suggestion of pip installing top2vec[indexing] and then tried pip installing hnswlib, however, I am still seeing this issue. Thanks for your help here!

Here is my pip freeze for reference: 
(legally_blurb) eknochenhauer@CHI-LX-L-035:~/repos/legally_blurb$ pip freeze
backcall==0.2.0
cycler==0.10.0
Cython==0.29.21
decorator==4.4.2
gensim==3.8.3
hdbscan==0.8.26
hnswlib==0.4.0
ipykernel==5.4.2
ipython==7.19.0
ipython-genutils==0.2.0
jedi==0.17.2
joblib==0.17.0
jupyter-client==6.1.10
jupyter-core==4.7.0
kiwisolver==1.3.1
llvmlite==0.35.0
matplotlib==3.3.3
numba==0.52.0
numpy==1.19.5
pandas==1.2.0
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
prompt-toolkit==3.0.10
ptyprocess==0.7.0
pybind11==2.6.1
Pygments==2.7.3
pynndescent==0.5.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.5
pyzmq==20.0.0
scikit-learn==0.24.0
scipy==1.6.0
seaborn==0.11.1
six==1.15.0
smart-open==4.1.0
threadpoolctl==2.1.0
top2vec==1.0.19
tornado==6.1
traitlets==5.0.5
umap-learn==0.4.6
wcwidth==0.2.5
wordcloud==1.8.1

**Comment by ddangelov** [comment]
It sounds like you trained the model with an older version of Top2Vec. I would try `pip install top2vec==1.0.16` or re-training with the latest version.

**Comment by ErinKnochenhauer** [comment]
Got it! Thanks for looking into this for me!

**Comment by nirvana1122** [comment]
I am getting this error with 1.0.26

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[154], line 1

----> 1 modelTV = Top2Vec.load(r"20230131.model")

File C:\Anaconda3\envs\base_ml\lib\site-packages\top2vec\Top2Vec.py:470, in Top2Vec.load(cls, file)
    467 top2vec_model = load(file)
    469 # load document index
--> 470 if top2vec_model.documents_indexed:
    471     if not _HAVE_HNSWLIB:
    472         raise ImportError(f"Cannot load document index.\n\n"
    473                           "Try: pip install top2vec[indexing]\n\n"
    474                           "Alternatively try: pip install hnswlib")

AttributeError: 'Doc2Vec' object has no attribute 'documents_indexed'
