### ISSUE TITLE
Start from arbitrary topics?

### ISSUE THREAD

**Issue by felixpoege** [ddangelov/Top2Vec#116]
Hi all,

I'm working on a dataset of patent texts, where documents are already grouped in topics (technology classes) by the patent office. I would like to group them into macro classes. Is there a way to get Top2Vec to help me in this regard? Dreaming, is it possible to set the document-topic association 'by hand' and then call `hierarchical_topic_reduction`?

Asking more specifically, if I instead of `cluster = hdbscan.HDBSCAN` in __init__ set my arbitrary clusters, and call all contents of __init__ arbitrarily, that should do it?

Thank you!

**Comment by ddangelov** [comment]
The topics are based on their semantic similarity, as well as the hierarchical reduction. I would try running Top2Vec on the patent texts, perform hierarchical reduction to a desired number and see how those map to your technology classes. 

If you could manually assign their topics, doing hierarchical reduction wouldn't necessarily give meaningful results with the way it currently works. I'll keep this use-case in mind for the future.
