### ISSUE TITLE
PicklingError: Can't pickle <class 'top2vec.Top2Vec.Top2Vec'>: it's not the same object as top2vec.Top2Vec.Top2Vec

### ISSUE THREAD

**Issue by p-dre** [ddangelov/Top2Vec#118]
Hi, the following code runes for four different models. By the fifth one I get the Error. I changed the 
.HDBSCAN min_cluster_size to 250. Can this change affect the model so extensively?

`PicklingError: Can't pickle <class 'top2vec.Top2Vec.Top2Vec'>: it's not the same object as top2vec.Top2Vec.Top2Vec`

```
import pickle
import pandas as pd
import top2vec as top
import numpy as np
import os

os.chdir(r'C:\Topic_model')
min_count = 30
modelname = 'top2vec' +'_'+ str(min_count)

with open(r"C:\Topic_model\documents_text.txt", "rb") as fp:
    documents_text = pickle.load( fp)  
    
with open(r"C:\Topic_model\documents_id.txt", "rb") as fp:
    documents_id = pickle.load(  fp)  
    
document = pd.DataFrame({'id': documents_id, 'text': documents_text})
document = document.drop_duplicates(subset='text')

documents_text = None
documents_id = None

model = top.Top2Vec(documents=document['text'], 
            speed="fast-learn", workers=7,
            min_count=min_count,
            keep_documents=False, 
            document_ids=document['id'])

model.save(modelname)
```

**Comment by ddangelov** [comment]
I unfortunately cannot help you with modified versions of Top2Vec.

**Comment by p-dre** [comment]
Thank you, I understand that, but I am a little bit surprised that this error happens. 
I also tried other sizes. With a minimum size of 200, the model works. Also with a size of 300.
 My hypothesis is that this error is caused by the combination of the size and structure of the data and the cluster size. It follows that the error could also occur with a cluster size of 15, if data with the appropriate size and structure were randomly given.
