### ISSUE TITLE
Why does Negative topic scores or word scores mean?? 

### ISSUE THREAD

**Issue by Alisha1992** [ddangelov/Top2Vec#119]
Hi,

Thanks for your quick responses always. It helps me alot. I have few questions on the top2vec package.

I was running it on a dataset and generated the topic scores and word scores. 

**The word scores and topic scores were Negative. What does a Negative score mean?? And how a Negative score gets generated?**

Your quick response will be of great help.

Thanks,
Alisha Panda

**Comment by ddangelov** [comment]
Negative word scores should mean highly dissimilar. Topics, documents, and words are all vectors. Those scores are the cosine similarity between the vectors. 

Which `embedding model` was used and how large was the dataset? Also what was the value of `min_count`?

**Comment by Alisha1992** [comment]
Hi,
Thanks for your quick response. I didnt specify any embedding model in the code and the dataset size was approximately 3500. Should i change any parameters over there??

Best,
Alisha Panda

**Comment by ddangelov** [comment]
`min_count` ignores all words with total frequency lower than this. For smaller corpora a smaller `min_count` will be necessary. I would try a value like 5. Also for a dataset of that size you could also try `embedding_model='universal-sentence-encoder-multilingual'`, as it is a pre-trained model. This could also improve results. 

You can find more details in the [Top2Vec API](https://top2vec.readthedocs.io/en/latest/api.html).

**Comment by Alisha1992** [comment]
Okiee. Thanks alot for your response. I will try out this solution for sure.
