### ISSUE TITLE
Inferring topics of unseen documents

### ISSUE THREAD

**Issue by angelaheumann** [ddangelov/Top2Vec#122]
According to https://github.com/ddangelov/Top2Vec/issues/5 is inferring topics of unseen documents already on your to-do list. Are there already progress on this topic?
We are a small team who wants to use top2vec for topic modelling but the missing inferring topics are a showstopper right now. If necessary we are willing to contribute to this project.
Thanks for your help/answer

**Comment by ddangelov** [comment]
There are some temporary solutions, see #63

**Comment by angelaheumann** [comment]
Thanks. That already helps a lot!

**Comment by n400peanuts** [comment]
Hello, I was wondering if is there any updates on this feature?
