### ISSUE TITLE
Issue when trying to load a saved model with a custom tokenizer

### ISSUE THREAD

**Issue by Dhruv26** [ddangelov/Top2Vec#126]
Hi. I created a Top2Vec model and passed a custom tokenizer to it. After saving it when I tried to load it, it throws an Error saying that it cannot find the tokenizer method in the current scope. The tokenizer that I passed was a simple function

![top2vec_error](https://user-images.githubusercontent.com/32687952/106608328-460bc200-658a-11eb-90c9-7770641c00e7.JPG)

Any chance this could be fixed?

**Comment by ddangelov** [comment]
This is now fixed, so if you train a new model you wont have that issue. If you want to be able to load your old model you will have to create:

```python
def _get_noun_phrases(text):
      return text
```

This wont be used for anything but it will allow you to load the model.
