### ISSUE TITLE
How to calculate PMI or any other Evaluation tool such as coherence score or confusion matrix?

### ISSUE THREAD

**Issue by PiyushKyushu** [ddangelov/Top2Vec#128]
In other topic modeling methods such as LDA and NMF, the optimal number of topics can found using coherence score and the confusion matrix can be build to check the accuracy. 
Is it possible to evaluate top2vec model with these kind of methods?

In paper, PMI is used to as an evaluation tool (comparison) but I am finding it difficult to implement it. It would be very helpful if you can share code for PMI calculation? or if can can share any tutorial for that?

Thanks!

**Comment by ddangelov** [comment]
See #17 #19 #30
