### ISSUE TITLE
The API Docs page is now blank after the most recent release

### ISSUE THREAD

**Issue by russelldc** [ddangelov/Top2Vec#129]
See my screenshot below. The page still loads, but it is empty. The Index and Module Index pages are also blank/missing. 

https://top2vec.readthedocs.io/en/latest/api.html

<img width="1381" alt="Screen Shot 2021-02-05 at 5 55 03 PM" src="https://user-images.githubusercontent.com/5100126/107105461-4cdd4380-67db-11eb-801c-e8c7be57ea8e.png">

**Comment by ddangelov** [comment]
Thank you for pointing that out, I will look into what happened.

**Comment by ddangelov** [comment]
Fixed, this was due to #125 preventing the API docs from being generated on readthedocs.
