### ISSUE TITLE
bytes-like object is required, not 'list'

### ISSUE THREAD

**Issue by aditm1993** [ddangelov/Top2Vec#13]
when run 
model = Top2Vec(documents=newsgroups.data, speed="learn", workers=8)

gives an error. 
<img width="752" alt="Screen Shot 2020-09-03 at 4 22 08 AM" src="https://user-images.githubusercontent.com/59645495/92044988-12d7c380-ed9d-11ea-934a-ea7934ef67d6.png">

**Comment by ddangelov** [comment]
Is the `newsgroups.data` a list of strings?

**Comment by ddangelov** [comment]
It seems to be a UMAP issue. I would try installing the latest Top2Vec and UMAP. I would try `pip install top2vec==1.0.10`. Additionally you can try `pip install umap-learn==0.4.6`.
