### ISSUE TITLE
Train model with new documents

### ISSUE THREAD

**Issue by paulthemagno** [ddangelov/Top2Vec#131]
Can I load an already trained Top2Vec model and add new documents (like new datasets) to continue its training without starting from scratch? 

I read from the function [add_documents](https://github.com/ddangelov/Top2Vec/blob/54e222f9dbc144ff432eb8c7c9a2358bd9cbcf7d/top2vec/Top2Vec.py#L1119) that if I insert a large quantity of data a new model should be created for better results. If I have understood, this function only puts the new documents in the clusters but doesn't update the topic vectors, so it should be useful for predictions, but not for training.

I'm searching for a sort of `resume_training` function which allows to train a model and then fine-tune it with new data in a second moment. 

Anyway thanks @ddangelov for this awesome work and for you availability.

**Comment by ddangelov** [comment]
If you use a sufficiently large model that is trained on data that is representative of the data being added it should work fine the way it is. The only thing that is not really being updated is the already learned document vectors, or new words that don't already exist in the model. The topic sizes are updated however.

Perhaps an option to be able to extend the vocabulary and recalculate the topics based on the new document density could be added in the future. 

What is your main motivation or need for fine-tuning?

**Comment by mirorac** [comment]
@ddangelov I have a similar question. My main motivation is to analyze the [dynamics](https://maartengr.github.io/BERTopic/getting_started/topicsovertime/topicsovertime.html) and trends of topics, as well as identify emerging topics ([incremental topic modeling](https://maartengr.github.io/BERTopic/getting_started/online/online.html)) in a continuous stream of documents (e.g., online posts). If I need to train a new model periodically, it becomes challenging to compare topics between different model instances.

Do you see a viable solution for this using Top2Vec? If it requires new development, I would be happy to contribute.
