### ISSUE TITLE
Terminated worker problem

### ISSUE THREAD

**Issue by nusipek** [ddangelov/Top2Vec#135]
I am trying to train a Top2Vec model with 50,000-100,000 documents. Although, I have tried few different versions of joblib, hdbscan and Top2Vec packages, the Top2Vec model always fails during 'finding the dense areas' phase. The error message;

*TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker*

The worker count does not matter since I have tried from 1 to 40 where the result is the same. I am running the model on a 128 GB RAM machine so the memory should not be an issue as well.

The problem occurs when I try to train models larger than 15,000 documents. (the total size for 15,000 is around 200 MB)

Current package versions;
top2vec==1.0.20
joblib==0.17.0
hdbscan==0.8.26

![Capture](https://user-images.githubusercontent.com/70028677/108179735-3b166d00-7106-11eb-8448-9ed4b249c4e7.PNG)

**Comment by ddangelov** [comment]
Use the latest version, `top2vec==1.0.23`.
