### ISSUE TITLE
Model Training Using Previously Trained Doc2Vec Embeddings

### ISSUE THREAD

**Issue by dkow72** [ddangelov/Top2Vec#137]
First and foremost thank you for this wonderful paper and package, it's really innovative and I am excited to experiment with it. Looking into the source code, I see that there are default parameters provided to the umap and hdbscan models used in Top2Vec. In the situation where I want to tune these parameters, I do not want to have to learn Doc2Vec embeddings all over again. Is there a way to input the Doc2Vec embeddings from the earlier trained Top2Vec model such that training of the new Top2Vec model can skip the initial Doc2Vec embedding learning component? Thank you!

**Comment by gmgeorg** [comment]
See https://github.com/ddangelov/Top2Vec/pull/39

**Comment by ddangelov** [comment]
I am going to add an option for providing pertained embeddings and models. It is on the to-do.

**Comment by dkow72** [comment]
@gmgeorg thanks!
@ddangelov awesome thank you for the update Dimo
