### ISSUE TITLE
How to get all documents for a topic?

### ISSUE THREAD

**Issue by LizMcQuillan** [ddangelov/Top2Vec#139]
It seems the num_docs argument doesn't accept a variable input or input above the number of documents in a given topic. Is there a way to get all documents for a given topic?

**Comment by hp0404** [comment]
If I got it right, try:
```python
from top2vec import Top2Vec


model = Top2Vec.load(...)

topic_num = 1
topic_docs = model.documents[np.where(model.doc_top==topic_num)]
```

**Comment by LizMcQuillan** [comment]
Sorry, my question was unclear. That solution doesn't maintain the topic number or any other metadata (i.e. scores). So, for example, if I wanted to do something like:

```
num_topics = top2vec_model.get_num_topics()
topic_sizes, topic_nums = top2vec_model.get_topic_sizes()
topic_doc_counts = list(zip(topic_nums, topic_sizes))

for i in range(num_topics):
    topic_sizes, topic_nums = top2vec_model.get_topic_sizes()
    documents, document_scores, document_ids = top2vec_model.search_documents_by_topic(topic_num=i, num_docs=topic_doc_counts[i][1])
    results = list(zip(documents, document_scores, document_ids))
    results_df = pd.DataFrame(results, columns = ['documents', 'document_scores', 'document_ids', 'topic'])
    results_df['topic'] = i
```

Using your proposed solution makes the iteration easier, but doesn't solve the assignment issue.

**Comment by ddangelov** [comment]
> Sorry, my question was unclear. That solution doesn't maintain the topic number or any other metadata (i.e. scores). So, for example, if I wanted to do something like:
> 
> ```
> num_topics = top2vec_model.get_num_topics()
> topic_sizes, topic_nums = top2vec_model.get_topic_sizes()
> topic_doc_counts = list(zip(topic_nums, topic_sizes))
> 
> for i in range(num_topics):
>     topic_sizes, topic_nums = top2vec_model.get_topic_sizes()
>     documents, document_scores, document_ids = top2vec_model.search_documents_by_topic(topic_num=i, num_docs=topic_doc_counts[i][1])
>     results = list(zip(documents, document_scores, document_ids))
>     results_df = pd.DataFrame(results, columns = ['documents', 'document_scores', 'document_ids', 'topic'])
>     results_df['topic'] = i
> ```
> 
> Using your proposed solution makes the iteration easier, but doesn't solve the assignment issue.

Using `top2vec_model.get_topic_sizes()` to get the topic sizes and then using the size of the topic of interest in the `num_docs` parameter of the `top2vec_model.search_documents_by_topic` function is the correct way of getting all documents of a topic.

```python

topic_of_interest = 5
topic_sizes, topic_nums = top2vec_model.get_topic_sizes()
documents, document_scores, document_ids = top2vec_model.search_documents_by_topic(topic_num=topic_of_interest, num_docs=topic_sizes[topic_of_interest])

```
