### ISSUE TITLE
bi-grams/ tri-grams supported keyword search (Including special character keywords)

### ISSUE THREAD

**Issue by kiran-kumar95** [ddangelov/Top2Vec#14]
hi @ddangelov,
could you please provide this additional feature on searching via keywords, as in current scenario its accepting only single tokenized keyword. 
**(example: search via "machine learning" instead of "machine" or "learning" )**
also while searching via tokens with special characters like "C#" or "C++" or "C" its unable to find any documents and throws an error saying **"model has not learnt those words during training"**, but those words are clearly present in the corpus.

**Comment by ddangelov** [comment]
The feature you are requesting already exists. The `keywords` parameter of `search_documents_by_keywords` accepts a list of strings, so you could pass it multiple keywords.

The special characters are a result of the default tokenizer, which removes them. It also removes any tokens shorter than 2 characters. There are two solutions to this, one is removing special characters from the search tokens. The other is passing a custom tokenizer to Top2Vec when training with the `tokenizer` parameter.

**Comment by kiran-kumar95** [comment]
i am able to pass multiple list of strings in **keywords** parameter, but its not accepting bi-gram/ tri-gram type keyword 
Eg: i need to pass keywords=['machine', 'learning'] to avoid any errors 
if i pass keywords=['machine learning', 'neural network'] it fails and throws error that model has not learnt that during training.

**Comment by ddangelov** [comment]
I am not sure why you expect it to do this, 'machine learning' is not one word, it is two separate words. Passing them as separate words is the correct way of doing the search. Alternatively you can pass Top2Vec a tokenizer which merges words that commonly appear together into phrases, however I would advice against this.
