### ISSUE TITLE
Accounting for plural nature of topic assignment

### ISSUE THREAD

**Issue by dkow72** [ddangelov/Top2Vec#141]
Would it be possible to allow for multiple topics to be returned for a given document, or at least the option for that. I.e. instead of get_documents_topics() returning just the topic id and the distance for the topic vector closest to a given document vector, we are able to retrieve for e.g. the 2nd and 3rd closest topic vectors too, along with their respective distances. 

So in the static method def _calculate_documents_topic() we return more than just the id and distance of the closest topic vector, but perhaps the next few closest topic vectors and their corresponding distances too. Thank you!

**Comment by sanchez5674** [comment]
Hi, 

For what's worth, that would also be helpful to me and, since you are calculating the distance between the vectors it might not be too hard to return a few more instead of just the top one. Thanks. 

Carlos

**Comment by ddangelov** [comment]
This will be added to the next version.

**Comment by russelldc** [comment]
@ddangelov Would the solution you're planning be generally better or more accurate than using `search_documents_by_vector()` as shown below?

`model.search_documents_by_vector(vector=model.topic_vectors[X], num_docs=Y)`
X = a single topic number
Y = total count of all input docs

**Comment by ddangelov** [comment]
It would be searching topics by documents, so it would be different.

**Comment by ddangelov** [comment]
Version 1.0.25 has `num_topics` parameter for `get_documents_topics`.
