### ISSUE TITLE
Number of documents needed when using universal sentence encoders

### ISSUE THREAD

**Issue by dulanafdo** [ddangelov/Top2Vec#142]
According to the documentation, the universal sentence encoder options are suggested for smaller data sets. Even though it says like that, when I'm trying to train the model using this line of code, 
`model = Top2Vec(documents, embedding_model='universal-sentence-encoder')`  

It gives me an error like this,
**ValueError: need at least one array to concatenate**

Based on the previous issues, I think, this error gives because of the insufficient length of the document list. 

**Then, to solve this, what should be the length of the document list?**

**Comment by doodyology** [comment]
I use the `universal-sentence-encoder` embeddings and have never encountered this error. Is the error being thrown by Tensorflow or something else? Also, are you passing a list of strings, not tokens, to the model?

**Comment by dulanafdo** [comment]
@doodyology I'm not sure whether the tensorflow throws this error or not. Yeah, I'm passing a list of strings to the model.

**Comment by ddangelov** [comment]
I believe this is due to the `min_count` parameter, which will remove all words with occurrence of less than 50 in the training data. I would try a lower value like `min_count=2` for very small datasets.

**Comment by utkarshshukla2912** [comment]
Facing this error too
