### ISSUE TITLE
Each time i pass in the same keyword, why do i land up with different topic numbers, documents and words??

### ISSUE THREAD

**Issue by Alisha1992** [ddangelov/Top2Vec#143]
Hi ddangelov,

Thanks for always answering the questions in quick time which helped me understand and use the package in better way. 
**Can you help me in understanding why do i land up with different set of documents , words and scores , though the keyword is same ?? For eg- keyword is cocoa, first run i get 4 different documents. 2nd iteration i get 4 different documents.** 
**Why is it so??**

Also, Can you help me know is there a way to get same results if i dont change my keyword?? Is there a way to set seed so that i land up with same set of results??

**Your quick response will be of great help**

Best,
Alisha Panda

**Comment by ddangelov** [comment]
Can you clarify what you mean? Are you training multiple models on the same data, are you using a specific function to search by keyword? Where is a keyword being used and what is changing?

**Comment by Alisha1992** [comment]
Hi ddangelov,

Thanks for your response. **Can you help me in understanding for the same keyword when searched in the data for 2nd or 3rd time, gives non consistent results in terms of top 'x' topics??** 

The process followed by me :
1) First model gets trained on 'Reviews' column
2) The model is saved and loaded 
3) Then particular seed keyword being passed like 'cocoa' search_topics(keywords=["cocoa"], num_topics=5)
4) The no of topics, words, scores returned for this keyword
5) **2nd time when i again start from training the model and repating all the process from 1 to 4, i see different results. Though the seed keyword is same i.e. cocoa.**

So, can you please help me understand why is it so?? And how do i get consistent result if the keyword is nt changed?

**Comment by ddangelov** [comment]
Which `embedding_model` are you using? If using `doc2vec` the word and document vectors learned will be slightly different each time due its stochastic nature. Additionally the UMAP stage is also stochastic. 

If you wanted more deterministic results there are som strategies discussed in #86. Additionally using one of the pertained options for `embedding_model` will also help.

**Comment by BonzoWhitesnake** [comment]
Thank you! Sorry for necromancy, but is it possible to set different number of training epochs using Top2Vec?
