### ISSUE TITLE
When I search for any keyword, sometimes I get " 'XYZ' has not been learned by the model so it cannot be searched".

### ISSUE THREAD

**Issue by PiyuPriya** [ddangelov/Top2Vec#145]
Hi ddangelov,

I have trained the model with whole data(data size :**230000**).when I search this model with some 'XYZ' word, for some words I get an error message saying " 'XYZ' has not been learned by the model so it cannot be searched".

**Code for training the model is as below :**
` mod1 = Top2Vec(documents = df1['doc'],min_count=2,speed = "learn", workers=100)
`
**It will be very helpful if I get a solution for this.**

Thanks,
Priyanka Marihal

**Comment by ddangelov** [comment]
If the word you are searching for has occurred less than `min_count` times then it won't be learned by the model. Are these very rare words you are searching?

**Comment by PiyuPriya** [comment]
I kept min_count = 0, then also getting same error. What if model has not learnt few words and while searching if we pass those words, we will end up with same error.
For ex: If we are passing list of words in the search function and one of the word is not learnet by the model,then  how to handle that error and get the output for other words in that list?

**Comment by ddangelov** [comment]
You could use pre-trained word embeddings externally to Top2Vec to find similar words to the word being searched which has been learned.

There will be a solution coming for this for embedding models that are per-trained and can embed out of vocabulary words.

**Comment by firmai** [comment]
Very much looking forward to this solution - it will really help in a current research project!

**Comment by franciscomelloc** [comment]
Just leaving a +1. Would be a really helpful fix.
