### ISSUE TITLE
delete_documents modifies topic_nums

### ISSUE THREAD

**Issue by jvanelteren** [ddangelov/Top2Vec#146]
As the title says. 

Trained a model:
model = Top2Vec(documents, speed='deep-learn', tokenizer=bigram_stopword_preprocess, workers=4)

searching for topic numbers before and after removing all documents from the model returns different results.
```
get topic nums from model.search_topics(keywords= ['klimaat'] , num_topics=4)

model.delete_documents(model,list(range(len(df))

get topic nums from model.search_topics(keywords= ['klimaat'] , num_topics=4) 
```

Playing around with monkeypatching delete_documents led me to this piece of code:
```
# update topics
    self._unassign_documents_from_topic(doc_indexes, hierarchy=False)
```
If I remove that line it works as supposed. So maybe something goes wrong in the _unassign_documents_from_topic

**Comment by ddangelov** [comment]
Are only the topic numbers different or also their descriptions?

**Comment by jvanelteren** [comment]
Only the numbers, topic words are identical.

**Comment by ddangelov** [comment]
That would be due to the topic sizes changing, and as things are currently the topic numbers are ordered by topic size.

**Comment by jvanelteren** [comment]
OK then it's known. I'll workaround it. I wanted to remove the documents to end up with a smaller file for web deployment. 

Thanks a lot for this great work btw!!
