### ISSUE TITLE
What would be the best way to incorporate NER?

### ISSUE THREAD

**Issue by datavistics** [ddangelov/Top2Vec#147]
Id like to use an NER to embed broader terms instead of just the unigrams.

Im not 100% sure how the unigrams are consumed. So if I wanted to embed "New York" instead of splitting it, what does the format of the output of the tokenizer need to be?

**Comment by datavistics** [comment]
Forgive the quick and dirty...

```
import spacy
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import strip_tags

nlp = spacy.load('en_core_web_sm')
NER_SPLIT = 'nernernerner'

def ner_tokenizer(doc):
    nlp_doc = nlp(doc)
    ner_clean_doc = doc
    for ent in nlp_doc.ents:
        ner_clean_doc = ner_clean_doc.replace(ent.text, ent.text.replace(' ', NER_SPLIT))

    tokens = simple_preprocess(ner_clean_doc, deacc=True, max_len=30)
    tokens = [token.replace(NER_SPLIT, ' ') for token in tokens]
    # tokens = [f'{w1} {w2}' for w1,w2 in zip(tokens[:-1], tokens[1:])]  # Quick and dirty bigrams
    return tokens

model = Top2Vec(clean_documents,
                tokenizer=ner_tokenizer,
                speed='deep-learn',
                embedding_model='universal-sentence-encoder',
                workers=8)
```

When I look at the topic words Im only seeing unigrams. Even if I just use the bigrams Im still only seeing unigrams. 
@ddangelov any ideas?

**Comment by ddangelov** [comment]
What does `ner_tokenizer` output? Each bigram should be a single string. Ex ["New York", "San Francisco"...]

**Comment by datavistics** [comment]
Yes, the output is a list of strings.

**Comment by ddangelov** [comment]
Can you paste an example output please?

**Comment by ddangelov** [comment]
I think I know what is going on, I'll have to look into fixing it. Thank you for pointing out the issue.

**Comment by datavistics** [comment]
Also, while you are looking at it, if there is a way to pre-tokenize (the input to the model would be documents and a tokenized documents). 

This would allow more efficient ways of tokenizing if the user wants.

**Comment by ddangelov** [comment]
That may have to be a long term goal but thank you for the suggestion.

**Comment by HCSS-StratBase** [comment]
It seems to me that what we'd really want here are noun phrases. This is also a standard approach in bibliometrics, btw.
NLTK, CoreNLP and spaCy have that (spaCy calls it noun chunks). But so if anybody has been able to do that for top2vec, it would be great if they could share this.
