### ISSUE TITLE
Iterator of documents as input

### ISSUE THREAD

**Issue by BenoitTS** [ddangelov/Top2Vec#148]
Hello,

I'd like to use Top2Vec for a big corpus that doesn't fit in memory: thus I have to read my dataset with an iterator. Would it be possible to accept such an input instead of imposing a list ? Gensim already supports this feature, I'm not sure about the other models.
Additionally, it would be even better to be able to pass a document already pre-processed, exactly what is produced when `use_corpus_file=True` so as to skip this step when doing experimentation.

Thanks for your library !

**Comment by ddangelov** [comment]
It should be possible, however it is not a priority at the moment.
