### ISSUE TITLE
GPU support for reduction in training time

### ISSUE THREAD

**Issue by kiran-kumar95** [ddangelov/Top2Vec#15]
Is there any parameter to enable faster training of model in 'deep-learn' mode using a GPU?
My model took around 8 hours to run in collab and was utilizing only CPU while training.
does increasing the number of workers (8 used in sample script) has an effect in accuracy or it just aids in speeding up the training time.

**Comment by ddangelov** [comment]
This model currently relies on CPU and does benefit from a multi-core environment. The more workers that are available the faster it will be, accuracy will not be affected. You can speed up training by using an environment with more workers, using 'fast-learn' or 'learn', and by setting the `use_corpus_file` parameter to True during training.
