### ISSUE TITLE
gensim latest release (4.0.0) breaks Top2Vec

### ISSUE THREAD

**Issue by annaledwoch** [ddangelov/Top2Vec#152]
Gensim had its latest version released a week ago, including major changes to its API (see: https://github.com/RaRe-Technologies/gensim/releases/tag/4.0.0). They replaced `docvecs` attribute of the Doc2Vec model with `dv` and removed `vectors_docs`, hence running Top2Vec results in the following error:

```
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    model = Top2Vec(documents, speed="test-learn")
  File "C:\<path>\Top2Vec\top2vec\Top2Vec.py", line 359, in __init__
    umap_model = umap.UMAP(**umap_args).fit(self._get_document_vectors(norm=False))
  File "C:\<path>\Top2Vec\top2vec\Top2Vec.py", line 560, in _get_document_vectors
    return self.model.docvecs.vectors_docs
AttributeError: 'KeyedVectors' object has no attribute 'vectors_docs'
```

The previous release (3.8.3) works fine.

**Comment by ddangelov** [comment]
I am just about to push a new version to address this! :)

**Comment by annaledwoch** [comment]
ah I see, thanks! Great project btw :)

**Comment by ddangelov** [comment]
Version 1.0.24 fixes the issue and is out.

**Comment by shelbywhite** [comment]
If this is truly compatible with Gensim 4.0.0, can you please update the requirements.txt to reflect this. Currently it keeps installing 3.8.3 which results in this error.
