### ISSUE TITLE
Out of the sample prediction

### ISSUE THREAD

**Issue by arsine1996** [ddangelov/Top2Vec#153]
Hi, thanks for the great package it is really awesome. But I have some problems, can I use the pertained model on the new sentences?  That is to use the model on out of the sample predictions.

**Comment by ddangelov** [comment]
What specifically do you mean by use it? You can train a Top2Vec model on a specific corpus, which will give you the topics of that corpus. You can then add new documents and get their topics. Is this what you are looking for?
