### ISSUE TITLE
Questions for Multilingual model

### ISSUE THREAD

**Issue by evangeliazve** [ddangelov/Top2Vec#154]
Hello support team,

First of all, thanks for this amazing work.
I would like to use top2vec with pre-trained model. My data are both in english and french so I found Universal Sentence Encoder Cross-lingual (XLING) is the most appropriate solution (https://tfhub.dev/google/universal-sentence-encoder-xling/en-fr/1)

Could you please precise how can I apply this with top2vec ?

Also, is there any way to train doc2vec with two languages ? Or should I translate data to a unique language before ?

I have a large data set (more than 2 million lines with sorth sentences) and I use Databricks with AWS. On that matter, I also need to know is all models can be saved in cloud environment. 

Any suggestions applying to my case are very welcome.

Best Regards,
Evangelia Zve

**Comment by ddangelov** [comment]
The `universal-senetnece-encoder` `embedding_model` should work for your task. The xling model is currently unavailable but I will look into adding more flexibility for embedding_models in the future.

With `doc2vec` you can train on multiple languages. However the languages will separate and so you will get separate topics in each language. With the `universal-senetnece-encoder` the two languages will be aligned and topics will be multilingual.

**Comment by evangeliazve** [comment]
Thanks a lot for the information.

Best Regards,
Evangelia
