### ISSUE TITLE
Setting 'embedding_model'

### ISSUE THREAD

**Issue by rollator3000** [ddangelov/Top2Vec#155]
Hi ddangelov,

I really like this repo & I'm fascinated by the results on the newsgroups data set in the given example - here everything works as expected.

When applying your approach to my (rather small & domain specific) data-set, the results with the default model 'Doc2Vec' are rather bad... Hence I tried to use the 'universal-sentence-encoder' instead -
` model = Top2Vec(documents, embedding_model='universal-sentence-encoder')`

Unfortunately this leads to the following error:
`TypeError: __init__() got an unexpected keyword argument 'embedding_model'`

I've reinstalled Top2Vec in a fresh environment & followed your instructions, but still received this error...

Thanks in advance!
Cheers Frederik

**Comment by rvolz** [comment]
The same here. The problem seems to related to #160. Although pip tries to install 1.0.24 it ends up with 1.0.11 when used with the universal-sentence decoders. And the install log shows the clear `WARNING: top2vec 1.0.11 does not provide the extra 'sentence_encoders'`.

**Comment by ddangelov** [comment]
You have to make sure you have the latest version of Top2Vec.

**Comment by wr0124** [comment]
same here, how to solve it ?

**Comment by v4fs** [comment]
@wr0124 , did you solve it?
