### ISSUE TITLE
Memory problem 

### ISSUE THREAD

**Issue by evangeliazve** [ddangelov/Top2Vec#156]
Hello support,

I tried to train top2vec model within databricks environment (aws) with sentence encoder and doc2vec but I received the following message : 

![image](https://user-images.githubusercontent.com/19437590/113986008-0e9ce880-984d-11eb-9aa8-4d0b919e6e8e.png)

I am working on approximately 2M rows and each row is between 2 and 4 words, not more...

Do you have any idea on how to resolve this ?
I suppose we can change driver or cluster memory limit. From your experience, would you know the approximate memory usage needed for this task ?

Thanks a lot for your support.

Best Regards,
Evangelia

**Comment by ddangelov** [comment]
What kind of memory do you have available at the moment? 

One strategy I would suggest is take a representative sample of your data, either half or even 500,000 rows and train the Top2Vec Model on that. Then use `add_documents` to add the rest. This might resolve your issue and give you comparable results.

**Comment by evangeliazve** [comment]
Hello,

Thank you for the quick reply and advices. Here are the cluster settings :

![image](https://user-images.githubusercontent.com/19437590/114023538-4d459980-9873-11eb-9403-1d788156a0ae.png)

Do you think is enough ?

Best Regards,
Evangelia

**Comment by ddangelov** [comment]
It really depends but I would try a smaller dataset or a subset for now. There should be a fix for large datasets coming in the near future.
