### ISSUE TITLE
Difficulties with distiluse-base-multilingual-cased

### ISSUE THREAD

**Issue by JakobBremer** [ddangelov/Top2Vec#159]
Hi, my documents are in Swedish so I need to use the distiluse-base-multilingual-cased as embedding_model. I have tried to install both with: 
pip install top2vec[sentence_transformers],
and:
pip install torch sentence_transformers,
as suggested when I get an error that looks like this:

/usr/local/lib/python3.7/dist-packages/top2vec/Top2Vec.py in _check_import_status(self)
    796         else:
    797             if not _HAVE_TORCH:
--> 798                 raise ImportError(f"{self.embedding_model} is not available.\n\n"
    799                                   "Try: pip install top2vec[sentence_transformers]\n\n"
    800                                   "Alternatively try: pip install torch sentence_transformers")

ImportError: distiluse-base-multilingual-cased is not available.

Try: pip install top2vec[sentence_transformers]

Alternatively try: pip install torch sentence_transformers

but it still does not work.. I hope you can help me, I really like your model and hope it will work for my project!

**Comment by ddangelov** [comment]
It sounds like you might be pip installing in the wrong environment. If using a notebook maybe restart your kernel after installing.
