### ISSUE TITLE
experiment with the arXiv full dump (4.3Gb)

### ISSUE THREAD

**Issue by x0rzkov** [ddangelov/Top2Vec#16]
Hi guys,

Hope you are all well !

I was wondering if it is possible to use the latest arXiv dataset available [here](https://kaggle.com/Cornell-University/arxiv) with top2vec. 

In a nutshell, I would like to extract topics from abstracts.

## to get the dump
```
gsutil ls gs://arxiv-dataset/metadata-v5/
gsutil cp gs://arxiv-dataset/metadata-v5/arxiv-metadata-oai.json .
```

Is it possible to index this dataset quickly as there is an update every week ?

Thanks in advance for your insights and inputs.

Cheers,
X

**Comment by ddangelov** [comment]
You can definitely do that!

**Comment by lucmichalski** [comment]
But how ? thanks for any help ^^

**Comment by lucmichalski** [comment]
Is there a way to replace Gensim and make gpu acceleration available ?

**Comment by ddangelov** [comment]
There is no GPU implementation of Doc2Vec that is faster than Gensim at the moment. This may be a future project but not at the moment. 

I trained a Top2Vec model on the YahooAnswers dataset, which contains 1.3 million posts, on my laptop and it took just several hours. Therefore you should be able to do this for the arXiv dump abstracts. If you want to speed up the process use a machine with more workers. Additionally set `use_corpus` to True, this makes parallelization more efficient.
