### ISSUE TITLE
numpy version missmatch when using universal-sentence-encoder

### ISSUE THREAD

**Issue by krlng** [ddangelov/Top2Vec#160]
using the universal-sentence-encoder requires tensorflow, which requires `numpy<1.20.0`, how ever the setup.py requires `numpy >= 1.20.0`. This makes it unclear how to use the universal-sentence-encoder option in top2vec.

**Comment by ddangelov** [comment]
It will work fine if you have numpy>=1.20.0 despite the tensorflow constraint.

**Comment by j1n6** [comment]
The conflict is caused by:
    tensorflow 2.4.1 depends on numpy~=1.19.2
    top2vec 1.0.24 depends on numpy>=1.20.0

Do you absolutely need 1.20.0?  

it might be ideal to align with tensorflow packaging so we can get the `pip install` smoothly....

**Comment by ianthomas** [comment]
So 2 thumbs ups, no changes and close the issue?   This is causing me problems, have you tried requiring numpy~=1.19.2 to see if you can get away with that?
