### ISSUE TITLE
How to determine the optimal number of topics?

### ISSUE THREAD

**Issue by hp0404** [ddangelov/Top2Vec#161]
I trained a model that resulted in 229 topics which are too much to interpret. I'd like to reduce that number - and I see the package has hierarchical topic reduction method. 

So my question is how to choose *the optimal* number of topics, e.g. how do I know if 30 topics is better than 15 or 50 etc.?

For LDA, we have *topic coherence*, but what should we use for Top2Vec?

**Comment by doodyology** [comment]
The paper uses PWI, but it isn't implemented yet. Others have tried implementing it, but without much success, as far as I can tell. See pages 9 through 11 in the paper, if you want to try to implement it yourself.

**Comment by ddangelov** [comment]
I will eventually have an implementation of PWI, it is just not priority at the moment. 

When you ask about optimal number of topics, I think that depends on your use-case. The fewer the topics the more high level they will be, and they will generally be the most prominent. The larger the number the more specific they will be. It really depends on what you will be using them for.

**Comment by momonga-ml** [comment]
@doodyology @ddangelov  Any recommendations for PMI implementations?
I found this one: https://gist.github.com/kdhein/00a99ca2bcd029e5dc95

@hp0404  If it helps, I am currently using Gensim's [CoherenceModel](https://radimrehurek.com/gensim/models/coherencemodel.html) to evaluate topics... There are other methods as well.
