### ISSUE TITLE
Is there any plan to implement K-means clustering?

### ISSUE THREAD

**Issue by yananchen1989** [ddangelov/Top2Vec#162]
Hello,

It seems that kmeans can handle the embeddings in high dimensions, therefore dimension reduction could be removed if we use k-menas clustering approach rather the dbscan?
Is there any plan to implement it and the evaluation module of information gain ?
Hoping further development.

**Comment by ddangelov** [comment]
K-means is not something that will be supported in the near-term. Topic information gain will eventually have its own repo.
