### ISSUE TITLE
[feature-request] Allowing to specify batch_size

### ISSUE THREAD

**Issue by annaledwoch** [ddangelov/Top2Vec#164]
I had issues with running top2vec with pre-trained universal-sentence-encoder as it required more memory than I had available on my machine. To be fair my computer does not have a lot of RAM, as I have only 8GB, but decreasing the batch_size allowed me to run the model without getting Memory Errors. Right now batch_size is fixed to 500, but I was wondering if allowing users to set batch_size as one of the arguments to initialise a model could be useful for people with less powerful machines? Thanks!

**Comment by ddangelov** [comment]
Thank you for the suggestion I will look into doing this.

**Comment by Raul9595** [comment]
Hi @annaledwoch, I am not sure if the repo is still being maintained so I have created a fork with the changes in my fork in case you want to check it out. I have listed the parameter added in the pull request.

**Comment by ddangelov** [comment]
The repo is still being maintained.

**Comment by Raul9595** [comment]
@ddangelov That's great to know! I've submitted a pull request for the above feature and would really appreciate if you could check it out.

**Comment by ddangelov** [comment]
`embedding_batch_size` now available in version 1.0.27
