### ISSUE TITLE
Error: Need at least one array to concatenate

### ISSUE THREAD

**Issue by JakobBremer** [ddangelov/Top2Vec#165]
Hi Dimo!
Could you help me interpret what is needed to be changed in my input data to remove this error, it is put in as list of strings and almost completed training:

<img width="1072" alt="Skärmavbild 2021-04-20 kl  15 28 58" src="https://user-images.githubusercontent.com/73175233/115404496-ab686a00-a1ed-11eb-9b5d-a55d3766a37b.png">

**Comment by ddangelov** [comment]
Try using a larger dataset or trying a smaller `min_count` 2-5 for very small datset.

**Comment by AbhiPawar5** [comment]
Hi @ddangelov , setting min_count did not work. Please let us know. Thanks!

**Comment by Lyba97** [comment]
Hi, I am facing the same issue.  @ddangelov
