### ISSUE TITLE
SavedModel file does not exist

### ISSUE THREAD

**Issue by dl-jgallego** [ddangelov/Top2Vec#168]
Hi,

Don't know why it is triggering this issue, I just called it like: 

Top2Vec(my_file, embbeding_model='universal_sentence_encoder_multilingual')

Does the embedding model needs to be previously saved? or does the function download it automatically?

**Comment by ddangelov** [comment]
It should be `embedding_model=universal-sentence-encoder-multilingual`. That kind of error also could be due to tensorflow issue, a computer or environment reset should fix it.
