### ISSUE TITLE
progress report during training ?

### ISSUE THREAD

**Issue by behrica** [ddangelov/Top2Vec#169]
As the training of a doc2Vec takes very long time, is it possible to have a progress report while it is running ?

I looked at the various options to Doc2Vec(..) , but did not find anything

**Comment by doodyology** [comment]
Just enable logging, something like this:
```python
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(sys.stdout))
```

**Comment by behrica** [comment]
Is this enough ?
I did a change to enable progress logging inside Doc2Vec via providing a callback and added tqdm in some places.

I just made a PR with the idea #171
