### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by siebeniris** [ddangelov/Top2Vec#17]
Hi Dimo,
thank you for this wonderful new tool for topic modeling.
I have tried out and used fastText embeddings and some simple additions for document vectors for my usage.
It works very well.
Could you also provide some examples for the evaluating information gain?

Thank you!

**Comment by ddangelov** [comment]
Great to hear! There will eventually be code with the information gain available. In the meantime you would have to implement the calculation as outlined in the paper.
