### ISSUE TITLE
umap issues in spark based environment

### ISSUE THREAD

**Issue by ConnorBarnhill** [ddangelov/Top2Vec#170]
Hello,

When trying to run this in a spark environment I get the following issue:
![image](https://user-images.githubusercontent.com/7959016/116607461-a2ffe580-a8f7-11eb-9686-589e35fef276.png)

I was able to trace this down to [an issue in umap/pynndescent](https://github.com/lmcinnes/umap/issues/477). It looks like users are reporting that it's resolved if versions are pinned to 0.5.0.

**Comment by ddangelov** [comment]
Thanks for sharing, once the umap/pynndescent issue is resolved this shouldn't be an issue.
