### ISSUE TITLE
Can we train the model with GPU?

### ISSUE THREAD

**Issue by kxlkxl1999** [ddangelov/Top2Vec#172]

**Comment by doodyology** [comment]
Not `doc2vec`, but you can train both the `universal-sentence-encoder` and `BERT` models with CUDA. It's easier for `BERT`: just install the [proper version of torch](https://pytorch.org/get-started/locally/). `universal-sentence-encoder` will normally consume all your GPU memory and crash your program unless you set a smaller batch size.
