### ISSUE TITLE
After hierarchical_topic_reduction, Adding a new document will make the return score much larger than the existing one.

### ISSUE THREAD

**Issue by haewanj** [ddangelov/Top2Vec#173]
After hierarchical_topic_reduction, Adding a new document will make the return score much larger than the existing one.

```
#doc2vec
model.hierarchical_topic_reduction(num_topics=200)

ids = ['20210203085134493', '20210203203555493']
model.add_documents(documents=X, doc_ids=ids)


topic_nums, topic_score, topics_words, word_scores = model.get_documents_topics(['20210203203555493'], reduced=True)
print(topic_nums, topic_score)

[128] [3.6663072]

documents, doc_scores, doc_ids = model.search_documents_by_topic(topic_nums[0], 10, reduced=True)
print(doc_scores)

[3.6663072  0.8881026  0.88421917 0.8841391  0.8799375  0.87896633
 0.8747963  0.8679556  0.86381793 0.8594839 ]
```

> 'search_documents_by_topic'
> - doc_scores (array of float, shape(num_docs)) – Semantic similarity of document to topic. The cosine similarity of the document and topic vector.
> 
> 'get_documents_topics'
> - topic_score (array of float, shape(doc_ids)) – Semantic similarity of document to topic. The cosine similarity of the document and topic vector.

In particular, it is a cosine similarity, which is larger than 1.0.

**Comment by ddangelov** [comment]
Which `embedding_model` are you using? Is this only the case for the reduced topics or also the original? Also what version of Top2Vec is this?

**Comment by haewanj** [comment]
I'm using the `doc2vec` and the latest version(1.0.24 gensim fixed)
And yes, this is only the case for the reduced topics. 

I'm looking at `_get_document_vectors` used in `hierarchical_topic_reduction`.
I don't understand, but it seems like not considering norm=True or False when using the `doc2vec`.

**Comment by ddangelov** [comment]
Ive located the error and it should be fixed in the next version.
