### ISSUE TITLE
AttributeError: module 'llvmlite.binding.ffi' has no attribute 'register_lock_callback'

### ISSUE THREAD

**Issue by giginghn** [ddangelov/Top2Vec#176]
I have already pip installed the top2vec, but when I run the command 
`from top2vec import Top2Vec`
It returns the error
`AttributeError: module 'llvmlite.binding.ffi' has no attribute 'register_lock_callback'`
I have tried multiple ways including this [thread](https://github.com/numba/numba/issues/6669) but it didn't solve the issue. Can anyone help?

**Comment by ddangelov** [comment]
This sounds like an isolated environment issue. I would recommend creating a fresh environment and installing the latest version of Top2Vec.
