### ISSUE TITLE
How to get score of a document according to each topic? 

### ISSUE THREAD

**Issue by jgrizou** [ddangelov/Top2Vec#178]
HI! Thanks for your work on Top2Vec, it is amazing!

I am trying to get a score/probability of a new document to belong to each of the topic. Something like:

`score_per_topic = model.score_document(document)`

where `score_per_topic` would be a list of probability (or similarity score) per topic `[P_topic0, P_topic1, P_topic2, ...]`.

This would be very helpful for analysing how the categorisation is done wrt. some categories we might access in another way. For example, if I have scientific documents I know are from Math and Geography fields, and Top2Vec outputs 5 topics, I would like to analyse which topic Math documents are associated with, etc

I could not find a way to do this looking into the code, do you have an idea where I could start?

**Comment by ddangelov** [comment]
For the time being you can use `add_documents` to add it to the model. This will only give you one topic however. There will be multi-topic capability in the future.
