### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'has_full_text'

### ISSUE THREAD

**Issue by dbl001** [ddangelov/Top2Vec#18]
In CORD-19_top2vec.ipynb, the attribute 'has_full_text' has been renamed:

E.g. from meatadata.readme:

* renamed "has_full_text" metadata column to "has_pdf_parse"
and this,
* consolidated metadata columns `has_pdf_parse` and `full_text_file` 
  into column `pdf_json_files`, which now stores the relative paths to the
  corresponding *.json files. note: this column is a ';' separated list of 
  paths (some rows have multiple associated pdf parses).

**Comment by ddangelov** [comment]
Thank you for the update, the dataset format has changed multiple times. The notebook will always work with the following snapshot of the data on [kaggle](https://www.kaggle.com/dangelov/covid19top2vec) which also contains the processed data.
