### ISSUE TITLE
How model is learning words when I have pretrained USE model?

### ISSUE THREAD

**Issue by jaytimbadia** [ddangelov/Top2Vec#180]
Hi, 

I am training Top2Vec on pretrianed USE. 
When I use model.similar_words(keywords=["buckbeak"]), it gives me relevant words from the corpus. Thats good.

But USE is not trained on "buckbeak", still it gives releant words.

I saw Top2Vec code for USE, I am not able to find where its training for pretrained models, and how come we 
are getting such similar words?

Thank you!!

**Comment by ddangelov** [comment]
The pre-trained USE model is trained on very large datasets and therefore has good representation of a wide range of vocabulary.
