### ISSUE TITLE
Getting better results with higher n_neighbors values in UMAP

### ISSUE THREAD

**Issue by doodyology** [ddangelov/Top2Vec#182]
Hey @ddangelov,

I am using Top2Vec for topic modeling on social media posts and have had great success. One area where I have had some issues though is in getting lots of micro-clusters in my results, some of which are summarized by very similar words to other topics and appear to be describing a highly similar underlying topic to other topics.

I've experimented with different ways around this, but have recently found that changing the `n_neighbors` parameter in UMAP to a much larger value, say `100` or even `300`, appears to be extremely helpful at getting rid of these micro-clusters, even while keeping the HDBSCAN parameters default at a minimum cluster size of  `15`. And the resulting topics look very good.

The paper recommends that for UMAP, `n_neighbors=15`. I guess my question is, what are the implications for increasing the `n_neighbors` parameter? My understanding is increasing this value means that UMAP preserves more of the global structure when constructing the embedding.

But given your recommendation of `n_neighbors=15`, do you think it's reasonable to increase this value?

**Comment by ddangelov** [comment]
I think this another way to control the granularity of the topics, the higher that `n_neighbours` is the more high level the topics will be. It definitely makes sense if it is giving you the results you are looking for. I think in cases where it's unclear what granularity of topics is necessary the default `n_neighbours=15` is a good start.

**Comment by doodyology** [comment]
That was my sense as well--thanks!
