### ISSUE TITLE
Cannot convert a symbolic Tensor to a numpy array.  This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

### ISSUE THREAD

**Issue by dbl001** [ddangelov/Top2Vec#184]
I am experimenting with Top2vec on Apple's Tensorflow for Mac with an AMD Radeio Pro 5700 XT.
Unfortunately, Apple appears to have archived the repository.
At no time did I see the GPU active for any embedding_model.

top2vec_trained = Top2Vec(documents=papers_prepared_df.text.tolist(), embedding_model="universal-sentence-encoder-multilingual", speed="learn", workers=6)

I tried with Anaconda Python 3.8, tensorflow 2.4.0-rc0 and numpy 1.19.1 as well as 1.19.5

```
% ipython         
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy

In [2]: print(numpy.__version__)
1.19.5

In [3]: import tensorflow

In [4]: print(tensorflow.__version__)
2.4.0-rc0

In [5]: print(numpy.__version__)
1.19.5

In [6]: quit
```
The exception is here:
``` 
self.word_vectors = self._l2_normalize(np.array(self.embed(self.vocab)))
Cannot convert a symbolic Tensor ({}) to a numpy array."
        " This error may indicate that you're trying to pass a Tensor to"
        " a NumPy call, which is not supported"
```

I tried doing the computation in tensorflow then converting to NumPy but it hasn't worked.
E.g. 
```
self.word_vectors = tf.math.l2_normalize(self.embed(self.vocab))
self.word_vectors = self.word_vectors.numpy()
```

**Comment by ddangelov** [comment]
I would create a fresh environment and install Top2Vec. It seems your numpy version may be the issue. The requirement is `numpy >= 1.20.0`.

**Comment by dbl001** [comment]
Support for the AMD GPU is [apparently] only in the tensorflow_mac implementation:

https://github.com/apple/tensorflow_macos

I also tried with numpy 1.20.3 but get the same error in:
```
File "/Users/davidlaxer/anaconda3/envs/tensorflow_mac/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 852, in __array__
    raise NotImplementedError(

NotImplementedError: Cannot convert a symbolic Tensor (StatefulPartitionedCall:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```
<img width="2560" alt="Screen Shot 2021-06-18 at 7 31 10 AM" src="https://user-images.githubusercontent.com/3105499/122577588-d1509600-d007-11eb-9980-43dd140e0232.png">

**Comment by dbl001** [comment]
btw - top2vec does run in a python 3.7 tensorflow 2.5 numpy 1.20.5 environment, just without utilizing AMD GPU which requires tensorflow_mac.
