### ISSUE TITLE
Can we use GPU for faster training  on large data using top2vec  

### ISSUE THREAD

**Issue by Itsneuralnet** [ddangelov/Top2Vec#185]
hi!
I have a custom data and wanted to use this package to train with top2vec. it take 6+ hours with deep learn, and take 35 min on fast learn  for a fraction of my dataset. I wanted to train all of it, can you suggest me something that can be useful to speedup the training process. I have a NVidia GPU 11GB.  is there any way to use this resource for it?

**Comment by ddangelov** [comment]
I would recommend using a different `embedding_model` with a pre-trained model like the `universal-sentence-encoder` it will be much faster. The default `doc2vec` is not set up for GPU, only CPU.

**Comment by Itsneuralnet** [comment]
thanks

**Comment by MarkWClements** [comment]
I second this. I really enjoy this package but it would be even better if the Doc2Vec implementation was able to use GPU's and was more customizable.
