### ISSUE TITLE
Is there a way to infer only the new corpus?

### ISSUE THREAD

**Issue by IanYu-GBI** [ddangelov/Top2Vec#187]
Hi! Thank you for the amazing lib. I have trained the model on a corpus of 70000+ documents, and I want to infer a new corpus of only 200 documents. Is there a way to perform topic modelling only on the new corpus but with the trained model? 
Because I wouldn't need the topics from the originally trained corpus (Kinda like how we'er using pre-trained BERT).

**Comment by ddangelov** [comment]
[query_topics](https://top2vec.readthedocs.io/en/latest/api.html#top2vec.Top2Vec.Top2Vec.query_topics) should do what you are looking for. Use the documents as the queries. Unless you want to create new topics based on the 200 documents. IN which case what `embedding_model` are you using?
