### ISSUE TITLE
Pre-trained Model subtitle misleading [documentation of readme.md]

### ISSUE THREAD

**Issue by humblemat810** [ddangelov/Top2Vec#190]
Intuition will lead us to think that the section is about loading a pretrained model as described in the top2vec paper, however,
it actually means the use the pretrained model in its underlying components.

Also, it will be nice to be able to have a way to load your model in the paper to validate/verify the promising results

**Comment by ddangelov** [comment]
Added clarification that it is pre-trained *embedding* models.
