### ISSUE TITLE
Getting ValueError while searching a topic for a given text (in string format)

### ISSUE THREAD

**Issue by devsinghh** [ddangelov/Top2Vec#194]
The following code is working fine with Doc2Vec embedding model. 
model.query_topics(query=query_text, num_topics=1, reduced=False, tokenizer=None)

However, when same code is used with 'distiluse-base-multilingual-cased' embedding model, following error surfaced:
ValueError: Vector needs to be of 512 dimensions.

Please suggest.

**Comment by devsinghh** [comment]
After training with universal sentence encoder model (topic modeling). Then tried using query_topics functionality to search a similar topic for a given string, following error is observed:

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  input must be a vector, got shape: []
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor/tokenize/StringSplit/StringSplit}}]]
  (1) Invalid argument:  input must be a vector, got shape: []
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor/tokenize/StringSplit/StringSplit}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/EncoderDNN/EmbeddingLookup/EmbeddingLookupUnique/embedding_lookup/DynamicPartition/_74]]

**Comment by ddangelov** [comment]
Thank you for pointing this out. I have fixed this issue and top2vec version 1.0.27 will reflect those changes.

**Comment by Fati-Hei** [comment]
I have the same problem. when I the function query_topics i get ValueError: Vector needs to be of 512 dimensions. I used  'distiluse-base-multilingual-cased' embedding model.

**Comment by vibl** [comment]
By the way, this lib is amazing. It is much better than any other semantic search libs I've tried.  I don't understand why it does not have ten times more stars. Thanks so much @ddangelov!
