### ISSUE TITLE
Training Doc2Vec with Corpus File Results in Permission Error on Windows

### ISSUE THREAD

**Issue by MarkWClements** [ddangelov/Top2Vec#196]
Hello,

When implementing top2vec under Windows 10 using embedding_model='doc2vec' and corpus_file=True, the script successfully generates the temporary file here in the `top2vec.py` script starting on line 290

```            
if use_corpus_file:
     processed = [' '.join(tokenizer(doc)) for doc in documents]
     lines = "\n".join(processed)
     temp = tempfile.NamedTemporaryFile(mode='w+t')
     temp.write(lines)
     doc2vec_args["corpus_file"] = temp.name
```
however, when trying to access the file later in Gensim's `doc2vec.py` script on lines 1313-1315

```
with utils.open(self.source, 'rb') as fin:
     for item_no, line in enumerate(fin):
          yield TaggedDocument(utils.to_unicode(line).split(), [item_no])
```
the call to `utils.open(self.source, 'rb') as fin:` give the error

`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\MCLEME~1\\AppData\\Local\\Temp\\tmp_njo370f'`

This issue appears to be related to 

[https://github.com/deepchem/deepchem/issues/707#issue-246546717](url)

In that Windows seems to have an issue with accessing a file if the `delete=True` option of `NamedTemporaryFile()`. 

A workaround is to just modify the source code and set `delete=False`, however, this will cause errors for Unix/Linux users. Is there a way to build in a fix for this that is platform agnostic?

**Comment by ddangelov** [comment]
I would just set `use_corpus_file=False`, it won't be significantly slower.
