### ISSUE TITLE
Not working for "distiluse-base-multilingual-cased" model

### ISSUE THREAD

**Issue by Yashsethi24** [ddangelov/Top2Vec#197]
I am not sure whether you or anybody else has checked this model using BERT models. It's not giving a correct output at all for the same newsgroup data.

Could you please check?

**Comment by ddangelov** [comment]
I just tried using the `distiluse-base-multilingual-cased` with top2vec version 1.0.26 and it works as expected. Can you be more specific about what doesn't work?

**Comment by harshgeek4coder** [comment]
> I am not sure whether you or anybody else has checked this model using BERT models. It's not giving a correct output at all for the same newsgroup data.
> 
> Could you please check?

Basically, you need to ensure that the specific dataset does not have any duplicate or null values.
If it does, then I would suggest removing them, and then try creating a model.
I had a similar experience with a dataset I was working on Earlier, when it had duplicate values or null values, the discovered topics were only 4.
Once I removed the duplicated strings in the corpus and dropped null values, it discovered topics up to 70.

**Comment by Yashsethi24** [comment]
![image](https://user-images.githubusercontent.com/68924343/130251252-8ea808a4-c99c-4f62-8ef5-bc3c49f9fa05.png)
![image](https://user-images.githubusercontent.com/68924343/130251303-ee1f3472-0bf4-47bb-a31e-ac7abce0eaab.png)
![image](https://user-images.githubusercontent.com/68924343/130251363-c77594a4-3411-4b31-b3b6-2ac0d0823636.png)

I ran the code using Google collab and sharing the results I got.
Please tell me what am I doing wrong?

**Comment by harshgeek4coder** [comment]
> ![image](https://user-images.githubusercontent.com/68924343/130251252-8ea808a4-c99c-4f62-8ef5-bc3c49f9fa05.png)
> ![image](https://user-images.githubusercontent.com/68924343/130251303-ee1f3472-0bf4-47bb-a31e-ac7abce0eaab.png)
> ![image](https://user-images.githubusercontent.com/68924343/130251363-c77594a4-3411-4b31-b3b6-2ac0d0823636.png)
> 
> I ran the code using Google collab and sharing the results I got.
> Please tell me what am I doing wrong?

I think you should use additional parameters like ```worker``` and ```speed``` in the model() function
it might improve the topic of discovering probabilities.

Here is an example :

```
Top2Vec(documents=corpus_list,speed='learn',workers=8,embedding_model='distiluse-base-multilingual-cased')
```

You can try both 'learn' and 'deep-learn'  in ```speed``` parameter for better results.
Please have a read at documentations as well.
Also, Feel free to ask any more queries you may have .

**Comment by Yashsethi24** [comment]
Already did. It didn't work.
Can you please share the code snippets and screenshots of result if possible?

**Comment by ddangelov** [comment]
Try passing the following to the model: 
`hdbscan_args = {'min_cluster_size': 10,
                'metric': 'euclidean',
                'cluster_selection_method': 'eom'}`
