### ISSUE TITLE
Inability to load in top2vec without crashing Jupyter kernel

### ISSUE THREAD

**Issue by christinabejjani** [ddangelov/Top2Vec#203]
Hello, I have been trying to simply load in top2vec: `from top2vec import Top2Vec`. Each time I do this, the kernel crashes. I tried a few things: I tried uninstalling Anaconda and reinstalling, including all the packages, in case some of the packages I had imported or installed were somehow having an effect. When I first tried loading in top2vec, it would tell me to `install top2vec[sentence_encoders]` or install tensorflow tensorflow_hub tensor_text, because it couldn't find the universal_sentence_encoder. (Sorry, I no longer have the exact error code, but from looking at the .py script, I believe it was those 3 packages). The first time, I couldn't get the top2vec[sentence_encoders] line to work, so I installed tensorflow tensorhub etc. Then the kernel crashing started. OK, so I assumed it was the tensorflow installation and reinstalled Anaconda and figured out that within Jupyter notebook on this Mac OS Big Sur 11.5.2, I'd need to add quotes around top2vec[sentence_encoders] (i.e., `!pip install 'top2vec[sentence_encoders]'`). I tried this installation, and it still didn't work: it still said it couldn't find the universal_sentence_encoder. When I google searched the issue, I saw this issue: https://github.com/ddangelov/Top2Vec/issues/77. I had the same exact issue as this person, but there was no solution listed. I also downloaded the universal_sentence_encoder from the tensorflow site, in case I could add that in, but without being able to import in top2vec, it didn't seem like that was a real solution. Googling showed this thread from tensorflow: https://github.com/tensorflow/tensorflow/issues/9829. I tried many things listed here, including `!conda update conda` and `!pip install -U numpy`. Numpy almost seemed to be having an issue: once I updated it, there was previously an issue with the load line, with mismatching versions of the cffi package, but that's no longer the issue - after I fixed that, it went back to crashing the kernel. I'm not sure what to do here? Please let me know if I need to put in more information here. (The packages I have loaded in the Jupyter notebook are: pandas, numpy, matplotlib.pyplot, seaborn, string, extract_text (from pdfminer.high_level), PyPDF2, urlopen, Request (from urllib.request), BeautifulSoup (from bs4), re, sys.)

**Comment by christinabejjani** [comment]
If it helps, I think it is the numpy version that is causing an issue. I also tried to install and run the package within a Google Cloud notebook and within a Google colab notebook. It first said `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/numpy-1.19.5.dist-info/METADATA' and then I went to install numpy 1.19.5 (pip install numpy==1.19.5) and it said `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject` where the StackOverflow issue suggests to uninstall and reinstall (https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp) and that just brought back the first error.

**Comment by christinabejjani** [comment]
Actually, turns out this is because there's an issue with Apple Sillicon / M1. While (https://towardsdatascience.com/installing-tensorflow-on-the-m1-mac-410bb36b776) this is designed to fix getting Tensorflow working, ultimately the issue while installing top2vec on the virtual machine (not general Anaconda) then becomes: https://github.com/numba/llvmlite/issues/693. I'm going to close this since this isn't necessarily specific to top2vec.

**Comment by MrPaulAlbert** [comment]
Hi Christina,  
Were you ever able to get Top2Vec to load on a M1 machine?  I'm facing your same problem with my kernel crashing.

**Comment by Emily-Chai** [comment]
How about using `conda install -c conda-forge top2vec` as mentioned in [https://anaconda.org/conda-forge/top2vec](url)? It works for me.
