### ISSUE TITLE
Documents not a list of strings error

### ISSUE THREAD

**Issue by Rothgargeert** [ddangelov/Top2Vec#204]
Hi Dimo,

I'm trying to run Top2Vec in Google Colab for my texts. When I check my df type is states "list." But when I run the Top2Vec model it states "Documents must be a list of strings."

[https://colab.research.google.com/drive/1raYvKHIUP9hmDFdi60fW6F0CLnyUDnNb#scrollTo=s9IB8Gf-M4YH](url)

Any help would be appreciated.

Thanks,
Roger

**Comment by sorenmc** [comment]
This solved it for me.
`model = Top2Vec(list(df["text"].to_numpy()))`

**Comment by ddangelov** [comment]
Make sure you cast the whole df column to string type before passing to Top2Vec as you might have mixed data types.

**Comment by mehrdad-dev** [comment]
dataset['text'] = dataset['text'].astype(str)
documents = dataset["text"].to_numpy()

It worked for me!

**Comment by ozi-dev** [comment]
> This solved it for me. `model = Top2Vec(list(df["text"].to_numpy()))`

god bless you mate

**Comment by GabrielOduori** [comment]
This has saved me bigly!
