### ISSUE TITLE
More Visualizations

### ISSUE THREAD

**Issue by Datanaught** [ddangelov/Top2Vec#205]
Hey I have a few visualizations you could add to the package if you are interested @ddangelov. One is a similarity matrix for the topics, another is related to plotting the clusters in different ways using the umap.plot module, and the last is a visualization for plotting topics over time. I would love if someone could help review and possibly fine tune these so that they can be added to the package!

**Comment by ddangelov** [comment]
Sorry for the late reply. Please feel free to submit a pull request.
