### ISSUE TITLE
Installation issue from numba and numpy

### ISSUE THREAD

**Issue by mjoy296-zz** [ddangelov/Top2Vec#206]
Numba needs NumPy 1.20 or less error. Full error stack below: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/36/j_203fcj42q9bvnlt1sl3j640000gp/T/ipykernel_86898/3328602876.py in <module>
----> 1 from top2vec import Top2Vec

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/top2vec/__init__.py in <module>
----> 1 from top2vec.Top2Vec import Top2Vec
          2 
          3 __version__ = '1.0.26'

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/top2vec/Top2Vec.py in <module>
         8 from gensim.utils import simple_preprocess
         9 from gensim.parsing.preprocessing import strip_tags
---> 10 import umap
        11 import hdbscan
        12 from wordcloud import WordCloud

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/umap/__init__.py in <module>
          1 from warnings import warn, catch_warnings, simplefilter
----> 2 from .umap_ import UMAP
          3 
          4 try:
          5     with catch_warnings():

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/umap/umap_.py in <module>
        26 from scipy.sparse import tril as sparse_tril, triu as sparse_triu
        27 import scipy.sparse.csgraph
---> 28 import numba
        29 
        30 import umap.distances as dist

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/numba/__init__.py in <module>
       196 
       197 _ensure_llvm()
--> 198 _ensure_critical_deps()
      199 
      200 # we know llvmlite is working as the above tests passed, import it now as SVML

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/numba/__init__.py in _ensure_critical_deps()
       136         raise ImportError("Numba needs NumPy 1.17 or greater")
       137     elif numpy_version > (1, 20):
--> 138         raise ImportError("Numba needs NumPy 1.20 or less")
       139 
       140     try:

ImportError: Numba needs NumPy 1.20 or less

I tried upgrading Top2Vec since I saw 1.0.23 'Added numpy>=1.20.0 dependency.' But this did not fix it.

**Comment by Fati-Hei** [comment]
I get the same issue

**Comment by sean-doody** [comment]
You have the wrong version of NumPy:

```bash
pip install numpy==1.20.0
```

**Comment by Fati-Hei** [comment]
For me the solution was installing fresh tensorflow.

**Comment by mangalm96** [comment]
> For me the solution was installing fresh tensorflow.

@Fati-Hei could you please share which version of tensorflow and numpy ended up working for you? And which python version you are using?

**Comment by Fati-Hei** [comment]
I used tensorflow-2.4.1-py3-none-any.whl to install Tensorflow on MacBook Air (M1)
