### ISSUE TITLE
How do you add new documents?

### ISSUE THREAD

**Issue by sarmientoj24** [ddangelov/Top2Vec#21]
Is there an API or any way to add new documents?
How does the code adapt new incoming documents?

**Comment by ddangelov** [comment]
You can use the `add_documents` method: https://github.com/ddangelov/Top2Vec/blob/425c3623c2aaf09a1b381d9c972fcbd1dd74f873/top2vec/Top2Vec.py#L525

**Comment by sarmientoj24** [comment]
So basically, the model is really a database containing all of your documents? 
Let me paraphrase my questions
- Do I need to add all my documents into the model and use the model like a database for querying? 
- If I have a new document, how do I get its topic using the model and find the nearest documents, topics, etc without inserting it to the model?

**Comment by ddangelov** [comment]
API guide is now available: https://top2vec.readthedocs.io/en/latest/api.html
