### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by zhaoyi1025** [ddangelov/Top2Vec#212]
Hi,
when I import top2vec, I got the issues.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-64-9a81163f0da9> in <module>
----> 1 from top2vec import Top2Vec

~\AppData\Roaming\Python\Python38\site-packages\top2vec\__init__.py in <module>
----> 1 from top2vec.Top2Vec import Top2Vec
      2 
      3 __version__ = '1.0.26'

~\AppData\Roaming\Python\Python38\site-packages\top2vec\Top2Vec.py in <module>
      8 from gensim.utils import simple_preprocess
      9 from gensim.parsing.preprocessing import strip_tags
---> 10 import umap
     11 import hdbscan
     12 from wordcloud import WordCloud

~\AppData\Roaming\Python\Python38\site-packages\umap\__init__.py in <module>
      1 from warnings import warn, catch_warnings, simplefilter
----> 2 from .umap_ import UMAP
      3 
      4 try:
      5     with catch_warnings():

~\AppData\Roaming\Python\Python38\site-packages\umap\umap_.py in <module>
     45 )
     46 
---> 47 from pynndescent import NNDescent
     48 from pynndescent.distances import named_distances as pynn_named_distances
     49 from pynndescent.sparse import sparse_named_distances as pynn_sparse_named_distances

~\AppData\Roaming\Python\Python38\site-packages\pynndescent\__init__.py in <module>
      1 import pkg_resources
      2 import numba
----> 3 from .pynndescent_ import NNDescent, PyNNDescentTransformer
      4 
      5 # Workaround: https://github.com/numba/numba/issues/3341

~\AppData\Roaming\Python\Python38\site-packages\pynndescent\pynndescent_.py in <module>
     14 import heapq
     15 
---> 16 import pynndescent.sparse as sparse
     17 import pynndescent.sparse_nndescent as sparse_nnd
     18 import pynndescent.distances as pynnd_dist

~\AppData\Roaming\Python\Python38\site-packages\pynndescent\sparse.py in <module>
      8 import numba
      9 
---> 10 from pynndescent.utils import norm, tau_rand
     11 from pynndescent.distances import kantorovich
     12 

~\AppData\Roaming\Python\Python38\site-packages\pynndescent\utils.py in <module>
      7 import numba
      8 from numba.core import types
----> 9 import numba.experimental.structref as structref
     10 import numpy as np
     11 

ModuleNotFoundError: No module named 'numba.experimental.structref'

How can I solve this problem?
Thanks in advance, look forward to your reply.

**Comment by ddangelov** [comment]
Looks like dependency issues, I would suggest creating a fresh conda environment and installing there.
