### ISSUE TITLE
How to use BERT Sentence Transformer properly?

### ISSUE THREAD

**Issue by TeTeTang** [ddangelov/Top2Vec#214]
It seems BERT Sentence Transformer now available for embedding, but which option we shall pass to 'embedding_model' in order to use the model?

**Comment by ddangelov** [comment]
Please refer to the [docs](https://top2vec.readthedocs.io/en/latest/?badge=latest).

**Comment by romanfrolovv** [comment]
> Please refer to the [docs](https://top2vec.readthedocs.io/en/latest/?badge=latest).

I do not think it is covered there
