### ISSUE TITLE
How to illustrate UMAP and HDBSCAN figures?

### ISSUE THREAD

**Issue by myrainbowandsky** [ddangelov/Top2Vec#217]
top2vec.py doesnot contain a clustering-figure-saving function.

If my understanding is correct,  then ,the clusters' number depends on:       https://github.com/ddangelov/Top2Vec/blob/f7d00feb260af328e95c09c8a378f329f1026e16/top2vec/Top2Vec.py#L370

Then, I just save the figure of hdbscan, right?

**Comment by ShawnCodesABit** [comment]
You can use the umap.plot package to get a good visualization of arbitrary vectors (topics) and embeddings (words, documents). Training a 2d UMAP and assigning labels based on index as demonstrated in the [Plotting UMAP results tutorial](https://umap-learn.readthedocs.io/en/latest/plotting.html) will allow you to get static or interactive plots which work well for large datasets.

Alternatively you can use the code as shown in [this PR](https://github.com/ddangelov/Top2Vec/pull/120/commits/8a59538f63c55215eda3a366dcf7f80216f56f7c) to generate a scatter plot of documents and topics.

Here's a quick example to plot topics versus terms.

```
# Where umap_args is what you passed into the Top2Vec constructor
umap_args_for_plot = umap_args.copy()
umap_args_for_plot.update({'n_components': 2,})

# If using the Top2Vec version on pip:
combined_vectors = np.vstack((top2vec_model.topic_vectors, top2vec_model._get_word_vectors()))
# If the Top2Vec version on git:
combined_vectors = np.vstack((top2vec_model.topic_vectors, top2vec_model.word_vectors))

# Assuming we want to label by type, could also label by closest topic number
type_labels = []
for index in range(len(combined_vectors)):
    if index < len(top2vec_model.topic_vectors):
        type_labels.append('topic')
    else:
        type_labels.append('term')
umap_plot_mapper = umap.UMAP(**umap_args_for_plot).fit(combined_vectors)
umap.plot.points(umap_plot_mapper, labels=np.array(type_labels), theme='fire')
```
