### ISSUE TITLE
How to predict the topic of a new document?

### ISSUE THREAD

**Issue by gongshaojie12** [ddangelov/Top2Vec#218]
When I completed the topic model training, and then I made topic predictions for new documents, but the predicted topics were the topics included in the model training data, which was obviously wrong. How can I use the trained model for topic extraction of new documents? Thank you very much!

**Comment by jstrick24** [comment]
You would need to convert your document(s) into a list where each element is a document(text), and document id(s) into 2 lists:
```
docs, doc_ids = list(texts), list(text_ids)
model.add_documents(docs, doc_ids)
topic_nums, topic_scores, topic_words, word_scores = model.get_documents_topics(doc_ids, num_topics=1)
```

**Comment by ddangelov** [comment]
Use the `query_topics` function and make the query your document.

**Comment by gongshaojie12** [comment]
Thanks a lot!
