### ISSUE TITLE
Is fine-tuning possible?

### ISSUE THREAD

**Issue by gouthamgithub** [ddangelov/Top2Vec#219]
First of all, thank you for this wonderful model.

When using the pretrained embedding option like USE, are we fine-tuning the existing model with our new dataset or are we just passing the new documents to find respective word snd document embedding?

**Comment by jstrick24** [comment]
Somewhat... The package does not have the functionality of measuring model performance, but there are ways to do that. This issue: Topic Information Gain implementation #158, @datanaught had a decent example that worked for me.

**Comment by humblemat810** [comment]
I have created a fork that allows for quick adjusting using hierarchical topic reduction, which use to be slow for amortised run time.
i.e. you can fine tune the number of topic reduction at this update
https://github.com/humblemat810/Top2Vec
