### ISSUE TITLE
"HTTPError: 403 Client Error: Forbidden for url" when trying to load "distiluse-base-multilingual-cased" model

### ISSUE THREAD

**Issue by oskrocha** [ddangelov/Top2Vec#225]
I get a HTTPError 403 error when trying to use the method Top2Vec with the sentence transformers 'distiluse-base-multilingual-cased' model: 

```
HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/sentence-transformers/distiluse-base-multilingual-cased/resolve/a8e5f372b71d062444f6a30409d678bb3d932247/.gitattributes
```

Anyone else has the same problem?

**Comment by ddangelov** [comment]
Hmmm I will look into this.

**Comment by ddangelov** [comment]
It looks like a naming convention change, it should be fixed in the next version. In the meantime I would recommend using `embedding_model='universal-sentence-encoder-multilingual'`.

**Comment by ddangelov** [comment]
After a closer look you shouldn't be getting this error. What version of top2vec and sentence-transformers do you have?
