### ISSUE TITLE
Stopwords as part of the topics 

### ISSUE THREAD

**Issue by ViksaaSkool** [ddangelov/Top2Vec#226]
Hey @ddangelov,

I was going trough the basic examples of the documentation and was testing your library to see if it fit my needs. 

In the **Benefits** section you state that "No stop word lists required.", yet I get "stopwords as part of the topic" (the input data are list of tweets). 

Am I doing something worng?

**Comment by ddangelov** [comment]
Which `embedding_model` are you using?

**Comment by ViksaaSkool** [comment]
I've reinspected everything and dig some more in the issues section of your repo. 
With the following line 👇🏻, it seems that I cannot reproduce the issue (having stopwords in the topics result).

`Top2Vec(documents = my_list_of_tweets, min_count = 2, embedding_model = 'universal-sentence-encoder')`

just a thought: maybe it'll be better, when you do a keyworad search or a query to not make the library return error (exception), but instead maybe return something that represents `None`?

Anyways, great library, I'll close the issue - thanks for your prompt response!

**Comment by phuclh** [comment]
@ViksaaSkool @ddangelov I just tested with my document. And  I still see some stop words like `is`, `are`, `use`
<img width="660" alt="CleanShot 2022-08-21 at 19 03 24@2x" src="https://user-images.githubusercontent.com/6707194/185824614-21ab08ab-a935-40d2-b1a5-52ba5522f64d.png">


This is the link to my documents: https://drive.google.com/file/d/1TtXioOHKaYFmes3XlfjYOsa2yZ2VHa2F/view?usp=sharing

Thank you!
