### ISSUE TITLE
Different topics when running same model

### ISSUE THREAD

**Issue by igorkf** [ddangelov/Top2Vec#23]
Why the same model create different topics every time I run it?   
   
Would be good to has a rgument to set a random_state, to ensure that the model will give the same topics every time is runned.

**Comment by ddangelov** [comment]
Doc2Vec and UMAP are both stochastic, therefore the topics will vary between runs. The larger the dataset is the less pronounced these differences will be. Also using 'deep-learn' as opposed to 'fast-learn' and 'learn' for `speed` will lead to less pronounced differences.

**Comment by igorkf** [comment]
Ok. I'm using `deep-learn` currently, but my corpus isn't too big.    
Thanks.
