### ISSUE TITLE
module 'umap' has no attribute 'UMAP'

### ISSUE THREAD

**Issue by Sallyzhu** [ddangelov/Top2Vec#230]
I ran one time, and after that always had the error. Thank you for helping. 
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/_m/rfx_5zls6sx5c3kyvv22m_wr0000gn/T/ipykernel_52148/2585775598.py in <module>
----> 1 top2vec = Top2Vec(documents=reddit_df_string, speed="learn", workers=4)

/opt/anaconda3/lib/python3.8/site-packages/top2vec/Top2Vec.py in __init__(self, documents, min_count, embedding_model, embedding_model_path, speed, use_corpus_file, document_ids, keep_documents, workers, tokenizer, use_embedding_model_tokenizer, umap_args, hdbscan_args, verbose)
    357                          'metric': 'cosine'}
    358 
--> 359         umap_model = umap.UMAP(**umap_args).fit(self._get_document_vectors(norm=False))
    360 
    361         # find dense areas of document vectors

AttributeError: module 'umap' has no attribute 'UMAP'

**Comment by schetudiante** [comment]
hey Sallyzhu,
I have faced the same issue.
Perhaps  , you can 
`import umap-learn'

this [link here](https://stackoverflow.com/questions/57242208/how-to-resolve-the-error-module-umap-has-no-attribute-umap-i-tried-installi) may help better

**Comment by havardl** [comment]
Make sure you install the correct library: 
`pip install umap-learn`
