### ISSUE TITLE
Error when querying documents with model using embedding_model

### ISSUE THREAD

**Issue by belma-m** [ddangelov/Top2Vec#233]
Hi,

when I initialized the model with the _embedding_model_='universal-sentence-encoder', and then tried to use the _query_documents_, I got the following error:
input must be a vector, got shape: []
	 [[{{node text_preprocessor/tokenize/StringSplit/StringSplit}}]] [Op:__inference_restored_function_body_4561]

The same query works just fine with a model without the _embedding_model_ option.
Thanks in advance for your help!

**Comment by ddangelov** [comment]
What code did you run exactly?

**Comment by belma-m** [comment]
```
model = top2vec.Top2Vec(input_data, embedding_model='universal-sentence-encoder')
model.query_documents(testString, 4)
```

**Comment by ddangelov** [comment]
I was not able to recreate this error.
