### ISSUE TITLE
Are topic vectors from different models comparable using "universal-sentence-encoder"?

### ISSUE THREAD

**Issue by ma-ji** [ddangelov/Top2Vec#235]
Thanks for the amazing work!

My question is, say I trained Model A with an English corpus and Model B with a Chinese corpus, both using `universal-sentence-encoder`. Are topic vectors from Model A comparable to those from Model B? Can I do further operations on these vectors? For example, put the two types of vectors in the same space and cluster them. 

My use case is, I want to measure the semantic distance between a new document to different types of topics, asking questions, for example, is document C more similar to English topics than to Chinese topics.

Thanks!

**Comment by ddangelov** [comment]
If you use the `universal-sentence-encoder-multilingual` embedding model then they will be comparable. You can get the topic_vectors vectors from your model like so `top2vec_model.topic_vectors` and their corresponding descriptions `top2vec_model.topic_words`. Distance between them will represent semantic similarity.
