### ISSUE TITLE
Gensim version required . . ?

### ISSUE THREAD

**Issue by i4meta** [ddangelov/Top2Vec#238]
Just noticed a discrepancy regarding **Gensim** version (in **Master**) between: 

**setup.py** 

`	'gensim < 4.0.0',`

**requirements.txt**

`	gensim>=4.0.0`

Has **Master** been successfully run against gensim>=4.0.0 . . ? Or is this still a work in progress for the next release?

**Comment by ddangelov** [comment]
New version `1.0.27` now reflects what is on master.
