### ISSUE TITLE
generate topics for 1 document

### ISSUE THREAD

**Issue by krrishdholakia** [ddangelov/Top2Vec#239]
Hi! 

Would it be possible to have this generate topics for 1 document? I'm trying to run this to generate topics on a conversation transcript, but i keep hitting: 

ValueError: k must be less than or equal to the number of training points

when i run: 

model = Top2Vec([document],embedding_model='universal-sentence-encoder')

**Comment by ryanon4** [comment]
You could break the transcript up into multple documents and then perform topic modelling on these, you would need more than 100 documents off the top of my head. 
`documents = document.split(".")` Is a basic way to split them based on a full stop representing the end of sentence, if you want something more advanced look into NLTK library:
`from nltk import sent_tokenize, word_tokenize`
`sentences = 'This is the first sentnece. This is the second. And this is the third'`
`documents = sent_tokenize(sentences)`

**Comment by ddangelov** [comment]
I would break the transcript up as suggested above.
