### ISSUE TITLE
Invalid embedding model

### ISSUE THREAD

**Issue by vistamou** [ddangelov/Top2Vec#241]
Hello, I'm trying to use another embedding model, from the ones provided here : https://github.com/ddangelov/Top2Vec/blob/master/top2vec/Top2Vec.py

`model4 = Top2Vec(documents,embedding_model='paraphrase-multilingual-MiniLM-L12-v2', speed="learn", workers=8, verbose=True)`

and I get a : `ValueError: paraphrase-multilingual-MiniLM-L12-v2 is an invalid embedding model.`

Could you please help?

**Comment by elashrry** [comment]
same thing happened with `"universal-sentence-encoder-multilingual-large"`. 

`top2vec = Top2Vec(docs, embedding_model="universal-sentence-encoder-multilingual-large")`

I got the same error 
`ValueError: universal-sentence-encoder-multilingual-large is an invalid embedding model.`

**Comment by kunal-bhadra** [comment]
Hey @elashrry, I'm facing the same issue. Can you please tell how you cloned the repo and used the Top2Vec class directly?

**Comment by elashrry** [comment]
Hello @kunal-bhadra, just like you clone any other repos. I cloned it to a subfolder of my project and imported the `Top2Vec` class from its module (`Top2Vec.top2vec.Top2Vec`).

**Comment by ddangelov** [comment]
New version `1.0.27` will fix this.
