### ISSUE TITLE
no matches found: top2vec[sentence_encoders] for any pretrained embedding model

### ISSUE THREAD

**Issue by ghltshubh** [ddangelov/Top2Vec#247]
Why am I getting `no matches found` for any pretrained embedding_model?

**Comment by ddangelov** [comment]
What are you trying to do?

**Comment by jamesreno2** [comment]
If you're having that issue trying to install via:

pip install top2vec[sentence_transformers]

you may have to put single quotes around 'top2vec[sentence_transformers]'
