### ISSUE TITLE
Training on own documents 

### ISSUE THREAD

**Issue by yugaljain1999** [ddangelov/Top2Vec#25]
I was training top2vec model on own documents but it is throwing an error: `Documents is not a list of strings` but I checked my preprocessed documents which looks like list of strings even then it is throwing an error..
@ddangelov @gclen  Please help me in this ...
Here is glimpse of some documents on which I wanna train this model..
![image](https://user-images.githubusercontent.com/32617984/92991970-c90d7c80-f504-11ea-8572-a443ad4ab9be.png)

How should I arrange these cleaned documents?
Thanks!

**Comment by ddangelov** [comment]
Have you tried to explicitly cast the documents as a list? Please send more details about the error itself.

**Comment by yugaljain1999** [comment]
@ddangelov Thanks for your response. I solved this error now, actually there is some noise in list of documents which can't be decode into str, so I simply removed those noisy documents.

**Comment by anon1789** [comment]
> I was training top2vec model on own documents but it is throwing an error: `Documents is not a list of strings` but I checked my preprocessed documents which looks like list of strings even then it is throwing an error.. @ddangelov @gclen Please help me in this ... Here is glimpse of some documents on which I wanna train this model.. ![image](https://user-images.githubusercontent.com/32617984/92991970-c90d7c80-f504-11ea-8572-a443ad4ab9be.png)
> 
> How should I arrange these cleaned documents? Thanks!

Hi, what was the fix of this? I am facing the same

**Comment by yugaljain03** [comment]
Simply remove those documents which is causing error as it only takes str object not bytes or anything else..

**Comment by anon1789** [comment]
> Simply remove those documents which is causing error as it only takes str object not bytes or anything else..

Sorry I'm a little bit new to this... how do I go about doing that? It's all one big text string from a 1 column csv

**Comment by yugaljain1999** [comment]
Simply don't consider that big string for now.
