### ISSUE TITLE
Failed to train model with about 2 millions of tweets [OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead]

### ISSUE THREAD

**Issue by lingechun** [ddangelov/Top2Vec#254]
Hi,

I downloaded the newest version top2vec==1.0.27 and trained my model with 2 millions of tweets. However, it stuck after overnight. Anyone has ideas how to fix it? Thanks!!!!

In [1]: import pandas as pd
   ...: import re
   ...: from top2vec import Top2Vec
   ...: import csv

In [2]: documents = pd.read_csv("data_measured75_Eng.csv", encoding ='utf-8', low_memory=False, lineterminator='\n')

In [3]: tweets = documents["clean_text"].to_list()

In [4]: model = Top2Vec(documents=tweets, workers=8, speed='learn', embedding_mo
   ...: del='doc2vec')
2022-04-06 22:19:05,461 - top2vec - INFO - Pre-processing documents for training
2022-04-06 22:22:30,013 - top2vec - INFO - Creating joint document/word embedding
2022-04-07 00:12:08,826 - top2vec - INFO - Creating lower dimension embedding of documents
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
^C
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-4-99241dc84e23> in <module>
----> 1 model = Top2Vec(documents=tweets, workers=8, speed='learn', embedding_model='doc2vec')

~/opt/anaconda3/lib/python3.8/site-packages/top2vec/Top2Vec.py in __init__(self, documents, min_count, ngram_vocab, ngram_vocab_args, embedding_model, embedding_model_path, embedding_batch_size, split_documents, document_chunker, chunk_length, max_num_chunks, chunk_overlap_ratio, chunk_len_coverage_ratio, sentencizer, speed, use_corpus_file, document_ids, keep_documents, workers, tokenizer, use_embedding_model_tokenizer, umap_args, hdbscan_args, verbose)
    666                          'metric': 'cosine'}
    667 
--> 668         umap_model = umap.UMAP(**umap_args).fit(self.document_vectors)
    669 
    670         # find dense areas of document vectors

~/opt/anaconda3/lib/python3.8/site-packages/umap/umap_.py in fit(self, X, y)
   2682 
   2683         if self.transform_mode == "embedding":
-> 2684             self.embedding_, aux_data = self._fit_embed_data(
   2685                 self._raw_data[index],
   2686                 self.n_epochs,

~/opt/anaconda3/lib/python3.8/site-packages/umap/umap_.py in _fit_embed_data(self, X, n_epochs, init, random_state)
   2715         replaced by subclasses.
   2716         """
-> 2717         return simplicial_set_embedding(
   2718             X,
   2719             self.graph_,

~/opt/anaconda3/lib/python3.8/site-packages/umap/umap_.py in simplicial_set_embedding(data, graph, n_components, initial_alpha, a, b, gamma, negative_sample_rate, n_epochs, init, random_state, metric, metric_kwds, densmap, densmap_kwds, output_dens, output_metric, output_metric_kwds, euclidean_output, parallel, verbose, tqdm_kwds)
   1076     elif isinstance(init, str) and init == "spectral":
   1077         # We add a little noise to avoid local minima for optimization to come
-> 1078         initialisation = spectral_layout(
   1079             data,
   1080             graph,

~/opt/anaconda3/lib/python3.8/site-packages/umap/spectral.py in spectral_layout(data, graph, dim, random_state, metric, metric_kwds)
    304 
    305     if n_components > 1:
--> 306         return multi_component_layout(
    307             data,
    308             graph,

~/opt/anaconda3/lib/python3.8/site-packages/umap/spectral.py in multi_component_layout(data, graph, n_components, component_labels, dim, random_state, metric, metric_kwds)
    241         num_lanczos_vectors = max(2 * k + 1, int(np.sqrt(component_graph.shape[0])))
    242         try:
--> 243             eigenvalues, eigenvectors = scipy.sparse.linalg.eigsh(
    244                 L,
    245                 k,

~/opt/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in eigsh(A, k, M, sigma, which, v0, ncv, maxiter, tol, return_eigenvectors, Minv, OPinv, mode)
   1685     with _ARPACK_LOCK:
   1686         while not params.converged:
-> 1687             params.iterate()
   1688 
   1689         return params.extract(return_eigenvectors)

~/opt/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in iterate(self)
    535     def iterate(self):
    536         self.ido, self.tol, self.resid, self.v, self.iparam, self.ipntr, self.info = \
--> 537             self._arpack_solver(self.ido, self.bmat, self.which, self.k,
    538                                 self.tol, self.resid, self.v, self.iparam,
    539                                 self.ipntr, self.workd, self.workl, self.info)

KeyboardInterrupt: 

In [5]: 

In [5]: model
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-1f8a688cae5d> in <module>
----> 1 model

NameError: name 'model' is not defined

**Comment by ddangelov** [comment]
I can't tell from this what the issue is. Have you tried installing a fresh environment with just Top2Vec to rule out dependency issues?
