### ISSUE TITLE
Constantly getting dependency conflicts when trying to use universal sentence encoder with tensorflow gpu

### ISSUE THREAD

**Issue by jstrick24** [ddangelov/Top2Vec#259]
Is there a very specific order in which packages need to be installed? I have gotten it to work multiple times, but I am constantly having create new environments or fix the one I am using at the time. I typically install tensorflow-gpu==2.5.0 first, then top2vec, then top2vec[sentence_encoders] last. Any help or advice would be greatly appreciated

**Comment by ddangelov** [comment]
I am not sure what dependency issues tensorflow-gpu causes but I will look into it. Please share any findings.
