### ISSUE TITLE
Top2Vec as an updating model

### ISSUE THREAD

**Issue by Uzay-G** [ddangelov/Top2Vec#263]
Hello,

I was wondering how feasible it would be to adapt top2vec or other topic modeling methods to make them online, as in you can update the model with new data as you go.

Would you have any advice on how one could do this in top2vec? would it be feasible?

I am seeding an initial top2vec model and then have a stream of new data, am wondering how I could best do this so I don't have to retrain the model each time.

**Comment by ddangelov** [comment]
Depending on the use-case and variability of the corpus you can just use the `add_documents` to add new documents to an existing model. If the corpus is constantly changing you will need to re-train the model occasionally. There will hopefully be a "re-compute topics" method coming soon.
