### ISSUE TITLE
No argument `embedding_model'

### ISSUE THREAD

**Issue by ddemszky** [ddangelov/Top2Vec#264]
When I install top2vec with the sentence encoders option, I get the error an unexpected keyword argument error for `embedding_model'. I think this is a gensim package clash version, but I tried multiple different gensim versions (3.8.1, 4.0.1), and keep getting the same error.

**Comment by ddangelov** [comment]
What version of `top2vec` do you have? Also what are you passing  `emebdding_model` ?

**Comment by ddemszky** [comment]
Unfortunately, I can't reproduce the error because I have now re-installed top2vec. However, now a new error I'm getting is that 'universal-sentence-encoder' does not exist, even though I installed top2vec with this option: `pip install 'top2vec[sentence_encoders]'.

I also have tensorflow installed. I have a Mac with an M1 chip.

Versions are:
Name: top2vec
Version: 1.0.11

Name: tensorflow-macos
Version: 2.8.0




ImportError                               Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 model = Top2Vec(documents=data[ESSAY_COL].tolist(),
      2                 document_ids=data["token_var"].tolist(),
      3                 embedding_model='universal-sentence-encoder',
      4                 speed="learn",
      5                 workers=8)

File ~/miniforge3/envs/py38_tf/lib/python3.8/site-packages/top2vec/Top2Vec.py:312, in Top2Vec.__init__(self, documents, min_count, embedding_model, embedding_model_path, speed, use_corpus_file, document_ids, keep_documents, workers, tokenizer, use_embedding_model_tokenizer, umap_args, hdbscan_args, verbose)
    309 self.embed = None
    310 self.embedding_model = embedding_model
--> 312 self._check_import_status()
    314 logger.info('Pre-processing documents for training')
    316 # preprocess documents

File ~/miniforge3/envs/py38_tf/lib/python3.8/site-packages/top2vec/Top2Vec.py:824, in Top2Vec._check_import_status(self)
    822 if self.embedding_model != 'distiluse-base-multilingual-cased':
    823     if not _HAVE_TENSORFLOW:
--> 824         raise ImportError(f"{self.embedding_model} is not available.\n\n"
    825                           "Try: pip install top2vec[sentence_encoders]\n\n"
    826                           "Alternatively try: pip install tensorflow tensorflow_hub tensorflow_text")
    827 else:
    828     if not _HAVE_TORCH:

ImportError: universal-sentence-encoder is not available.

Try: pip install top2vec[sentence_encoders]

Alternatively try: pip install tensorflow tensorflow_hub tensorflow_text
