### ISSUE TITLE
Get topics, keywords and word clouds give correct answers but documents are wrong.

### ISSUE THREAD

**Issue by sarmientoj24** [ddangelov/Top2Vec#27]
I used deep-learn as method and use_corpus=True. I think that the suggested documents are wrong as it is not related to the keywords or the topic at all.

Training:
`model = Top2Vec(documents=new_products, speed="deep-learn", workers=16, verbose=True, use_corpus_file=True)`
But finding similar words and topics seem to work.

Created word cloud
![image](https://user-images.githubusercontent.com/8830319/93068755-7b814300-f6af-11ea-9ab4-9000e877f21c.png)

Documents related to Topic 1799 (WRONG)
![image](https://user-images.githubusercontent.com/8830319/93068857-9358c700-f6af-11ea-94db-e32657ce94b5.png)

Documents related to bicycle (wrong)
![image](https://user-images.githubusercontent.com/8830319/93068958-af5c6880-f6af-11ea-9dc8-1db97ae96c70.png)

Topics related to bicycle (correct)
![image](https://user-images.githubusercontent.com/8830319/93069044-c733ec80-f6af-11ea-87d7-e02eee303226.png)

**Comment by ddangelov** [comment]
Your documents look fairly short and a lot of the tokens also look like they could be rare. Try reducing the `min_count` parameter. It is set to 50 by default, this could be getting rid of most of the tokens in some documents.

**Comment by sarmientoj24** [comment]
My current tokens are around 3300 generated by the model. I also used it before and it actually outputs the right one so I am not sure if the problem is my parameters.

**Comment by ddangelov** [comment]
3300 is a fairly small number of tokens for what appears to be documents in the 100,000s. Have you tried changing `min_cont` to a smaller number yet?

**Comment by sarmientoj24** [comment]
Not yet. Doesn't min_count only adjust the least number of topics it could have? So should I just increase it?
I actually got a good one before with this. Just when I changed the parameters, it changed to that. Only those documents are wrong but the topics are correct.

**Comment by ddangelov** [comment]
`min_count` ignores all words with total frequency lower than this. For smaller corpora a smaller min_count will be necessary, as per the [API documentation](https://top2vec.readthedocs.io/en/latest/api.html). You would want to decrease it, the problem is likely what I in my initial comment.
