### ISSUE TITLE
error when use pre-trained embeddings

### ISSUE THREAD

**Issue by datatellingd** [ddangelov/Top2Vec#271]
I am using Jupyter Notebook with latest Anaconda with Python 3.9.13. 
I succeeded in running the example: 
model = Top2Vec(documents=newsgroups.data, speed="learn", workers=8)
However, when I tried to use the pertained models with: 
model = Top2Vec(documents=newsgroups.data, embedding_model='universal-sentence-encoder') 
It gave error message as "ImportError: universal-sentence-encoder is not available." 
It did the same even after I install the pre-trained model with command "pip install top2vec[sentence_encoders]".
I tried to do it in both MacBook Pro (1 Intel Chip and 1 Apple M1 chip) and both gave me same error message. 
Can you let me know how to solve this issue?

**Comment by tommykangdra** [comment]
I have the same issue with this one. Can anyone help to solve this issue?

**Comment by LichtenbergM** [comment]
Hello, you could try pip install 'top2vec[sentence_encoders]'

**Comment by ddangelov** [comment]
pip install 'top2vec[sentence_encoders]' should solve it.
