### ISSUE TITLE
Question: why does the `query_topics()` method return (slightly) different results when called with the same inputs?

### ISSUE THREAD

**Issue by next-game-solutions** [ddangelov/Top2Vec#273]
### Set-up
* a doc2vec-based model, trained from scratch (on 100K docs)
* the original number of topics found by the algorithm is reduced to a smaller, more manageable number
* running the `query_topics()`method with the same `query` string and requesting, say, `num_topics=3` and `reduced=True`

### Observed behaviour
* the returned topic similarities vary from call to call
* this _usually_ doesn't change the set and rank order of the identified topics; however, sometime lower-rank topics may change

### Question
Is this non-deterministic behaviour to be expected because that's how the (approximate?) search in the vector space works under the hood?

**Comment by ddangelov** [comment]
I would have a look at https://radimrehurek.com/gensim/models/doc2vec.html#gensim.models.doc2vec.Doc2Vec.infer_vector, but essentially Doc2Vec embedding is stochastic. 

If you dont want this behaviour I would recommend `embedding_model='universal-sentence-encoder-multilingual'`
