### ISSUE TITLE
Difference between "query_topics" and "add_documents"?

### ISSUE THREAD

**Issue by dror-kris** [ddangelov/Top2Vec#278]
Hi, I have trained a model on half of my large corpus and want to analyze the rest of my corpus using the existing model.

As far as I understand there are two possible methods to doing this - 
either running a ```query_topics()``` over each individual document, or adding the list of new documents via ```add_documents()```.

What is the difference between the two?

**Comment by ddangelov** [comment]
Please refer to https://top2vec.readthedocs.io/en/latest/api.html
