### ISSUE TITLE
Is there any way to find the optimize Number of Topics ?

### ISSUE THREAD

**Issue by Vela-zz** [ddangelov/Top2Vec#281]
I have read your paper and found that in you Paper Figure 6., when the number of topics go from 20 to 100, there are still considerable gain in INFORMATION GAIN index.  

so How many Topics are there till the INFORMATION GAIN becomes convergence?

and another question,

I found it is difficult to control the number of topics by HyperParameter because of HDBSCAN, what is the method you use to control the number of topics TOP2VEC would generate when  you paint Figure 6.  ? or if I change the CLUSTER MODEL to K-Means, are there any obvious shortcomings ? 
<img width="474" alt="figure6" src="https://user-images.githubusercontent.com/59645193/175479479-3f23d9ac-df8f-4882-8928-db852355a4b9.png">

**Comment by ddangelov** [comment]
Maximum information gain will occur when you have on topic per document, however that is not very useful. The optimal number of topics depends on the granularity of topic you want, which is often subjective and problem dependant. You can use `hierarchical_topic_reduction` to reduce the number of topics.
