### ISSUE TITLE
Process killed in "Creating lower dimension embedding of documents" step

### ISSUE THREAD

**Issue by mehrdad-dev** [ddangelov/Top2Vec#282]
I tried to train the model on 1 million documents, but when this step started I saw that top2vec was killed.

RAM:  32 G
CPU: Intel Xeon E312xx
OS:  ubuntu
speed:  fast-learn

Does anyone have an idea?
Is it about memory?
@ddangelov

**Comment by sean-doody** [comment]
Two things to try:

1. Pass a `UMAP` parameter dictionary and set `"init": "random"`.
2. Pass a `UMAP` parameter dictionary and set `"low_memory": True`.

**Comment by mehrdad-dev** [comment]
Thank you so much!
It's worked!
