### ISSUE TITLE
Unable to install top2vec by conda as well as pip

### ISSUE THREAD

**Issue by PawarKishori** [ddangelov/Top2Vec#285]
I am unable to install top2vec

Conda:
conda install -c conda-forge top2vec
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - failed

pip:
ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects

**Comment by sean-doody** [comment]
`HDBSCAN` can be a very frustrating library to install. Try these steps:

1. First, make a fresh `conda` environment:
```
conda create -n top2vec python=3.9
```
2. Install `HDBSCAN` ***before anything else*** through `conda` (**NOTE:** do *not* use pip):

```
conda install -c conda-forge hdbscan 
```
3. Then install `top2vec` with pip:
```
pip install top2vec
```

Additionally, if you're on Windows, you may need to install [Windows C++ Build Tools](https://stackoverflow.com/questions/40504552/how-to-install-visual-c-build-tools). However, if you install `HDBSCAN` with `conda`, you might be okay—I believe `conda` will install these for you.

**Comment by PawarKishori** [comment]
It worked on Ubuntu. Thanks :)

**Comment by phuclh** [comment]
@sean-doody How can I run conda in the Docker? Thank you!
