### ISSUE TITLE
Top2Vec AttributeError

### ISSUE THREAD

**Issue by LichtenbergM** [ddangelov/Top2Vec#289]
Hello,

I don't know what causes the issue but I work on an M1 Mac.
Sometimes I could create without any problems in my Jupyter Notebook my model with:
`model = Top2Vec(docs, speed='deep-learn', workers=8)`
but now I receive the following error:

`AttributeError: 'KeyedVectors' object has no attribute 'vectors_docs'`

Similar when I want to use an embedding system, sometime it works an half an hour later embedding systems aren't specified.

**Comment by ddangelov** [comment]
This looks like an environment issue. I would create a fresh environment.
