### ISSUE TITLE
What is the max limit of document length ?

### ISSUE THREAD

**Issue by sivachaitanya** [ddangelov/Top2Vec#293]
Thanks for the great package, From the documentation I understand we can extract topics for short documents of length 2-4 sentences. But can I pass in documents of length 3 pages text and expect topic modeller to come up with topics ?

**Comment by jstrick24** [comment]
I have used almost up to 500,000 if that helps at all

**Comment by ddangelov** [comment]
This depends on the embedding model used. I would look up each individual one, but for example the `universal-sentence-encoder-multilingual` has not limit. That being said for optimal results I would suggest chunking your documents into smaller chunks.
