### ISSUE TITLE
How to produce document-topic matrix?

### ISSUE THREAD

**Issue by rja122277** [ddangelov/Top2Vec#294]
Using Top2Vec may not be the best way to analyze different topics related to each document, but is there any way to produce a document-topic matrix here? I want to get each document's similarity scores with all available topics and construct a data frame for all documents. Thank you!

For your information, here is the code I'm using:
model = Top2Vec(
    data, 
    min_count=50, 
    ngram_vocab=True, 
    embedding_model='all-MiniLM-L6-v2', 
    embedding_batch_size=32, 
    umap_args={'n_neighbors':10, 'n_components':2}, 
    hdbscan_args={'min_cluster_size':10, 'min_samples':1}, 
    workers=4)

**Comment by sean-doody** [comment]
You can easily do this with cosine similarity:

```python
from sklearn.metrics.pairwise import cosine_similarity

topic_vectors = model.topic_vectors
doc_vectors = model.document_vectors

doc_topic_sims = cosine_similarity(doc_vectors, topic_vectors)
```

**Comment by rja122277** [comment]
I searched for this for a long time, and you gave me a solution in less than an hour. Thanks a ton!!
