### ISSUE TITLE
topic_words show words that do not exist in the topic's documents

### ISSUE THREAD

**Issue by ronirg** [ddangelov/Top2Vec#298]
I'm using top2vec version 1.0.27 on a small dataset of tweets (93 documents).
The call that I use -
model = Top2Vec(docs, embedding_model='universal-sentence-encoder', min_count = 5)   
I'm getting two topics (0,1).

topic_words, word_scores, topic_nums = model.get_topics(2)
print(topic_words)

when I print the topic_words I get the same words in a different order.
some of the words don't appear at all in the documents that were assigned to topic 0.

what can be the reason?

**Comment by wjbmattingly** [comment]
I had this happen to me as well. I don't have an answer here but I have a guess. First, 93 documents is quite small for Top2Vec unless you pass special arguments to hdbscan. Second, unlike other topic modeling approaches (like BERTopic), Top2Vec embedds the topics, documents, and words all in the same vector space. In most topic modeling approaches, the words are generated from the words used in the documents of a specific topic. This would make sense. Top2Vec, however, I believe generates the words from the embeddings that are closest to the topic centroid. In cases with a large quantity of documents, this usually works out to words appearing in close proximity to the centroid that appear in the documents of a given cluster. When you only have 2 clusters, Top2Vec has migrated the outliers into one of the two. This means that a lot of outliers are likely sitting inside both clusters that may be further removed from the centroid than the words embeddings are to the topic centroid. In this scenario, you get topics whose words are not matched to the documents of the topic. Again, this is just a guess.

**Comment by ddangelov** [comment]
> I'm using top2vec version 1.0.27 on a small dataset of tweets (93 documents). The call that I use - model = Top2Vec(docs, embedding_model='universal-sentence-encoder', min_count = 5) I'm getting two topics (0,1).
> 
> topic_words, word_scores, topic_nums = model.get_topics(2) print(topic_words)
> 
> when I print the topic_words I get the same words in a different order. some of the words don't appear at all in the documents that were assigned to topic 0.
> 
> what can be the reason?

A dataset of only 92 documents is too small.
