### ISSUE TITLE
Topics are not reduced

### ISSUE THREAD

**Issue by waguken** [ddangelov/Top2Vec#309]
I want to match the number of topics to compare the two cluster results, so I am doing a topic reduction to match the fewer results as shown below, but the topics are not reduced. Am I using "hierarchical_topic_reduction" incorrectly?

#
top2vec_model2 = Top2Vec2(docs2)
num_TP2=top2vec_model2.get_num_topics()
print(num_TP2)
vector = top2vec_model2.topic_vectors
print(vector)

top2vec_model = Top2Vec2(docs)
top2vec_model.hierarchical_topic_reduction(num_topics=num_TP2)
num_TP=top2vec_model.get_num_topics()
print(num_TP)
answer = top2vec_model.topic_vectors
print(answer)

#
2
[[-0.02735749 -0.14793424 -0.03798979  0.08646312 -0.13375823  0.07312864
  -0.13130635 -0.0852191  -0.01319341  0.0766216   0.06985436 -0.04766947
  -0.04045229  0.10620157  0.02115441  0.06043163 -0.02152634  0.18805307
   0.03540967 -0.2523699   0.07984492 -0.10128973  0.10114916 -0.0549325
   0.10377856  0.10887141 -0.06948288  0.25524095 -0.00078242 -0.01980954
   0.00610596  0.04988633  0.12702751 -0.08094335  0.04760743 -0.01696491
  -0.02807494 -0.23571794 -0.13709903 -0.01071483 -0.21168572 -0.0385176
   0.04477173 -0.06913009  0.08759107 -0.04348125 -0.01368985  0.04638526
   0.2443801  -0.0032759   0.17275871  0.06275795  0.17257941  0.09088091
   0.04673745 -0.07423776 -0.12968145  0.06442445  0.08650976 -0.1762831
   0.06192505 -0.00965873 -0.05626255 -0.02348878  0.07935343 -0.02457177
   0.09963544 -0.04979764 -0.00862315  0.0921112  -0.0391288   0.06584268
   0.04321415 -0.09762327  0.00420422 -0.1125628  -0.07345535 -0.4006077
   0.10203972 -0.2414451 ]
 [ 0.04736513  0.08306479  0.0667057   0.14386873  0.14955819  0.07301553
  -0.05444815  0.01019049 -0.04985784 -0.11203341 -0.12269652  0.00151094
  -0.01683964 -0.13468574  0.15401119 -0.14413096 -0.2964828  -0.05981901
   0.03651946  0.1814995  -0.14331383  0.18235634 -0.01739823  0.11319201
  -0.04766539  0.0068115   0.17598635 -0.04399584  0.01063922 -0.02894907
  -0.06082349  0.11137056 -0.04780626  0.22539109  0.07098878  0.22468628
   0.00211189  0.23287117 -0.01159555  0.09850271  0.09958462  0.06774913
  -0.14961372  0.08110867 -0.07216198  0.05907191  0.07486276  0.14337397
  -0.17953438  0.08922016  0.12639786 -0.15604924 -0.00278476 -0.09517763
  -0.09959437 -0.13903755  0.14954966  0.02826839  0.00807701 -0.07520797
  -0.06472301 -0.05874422 -0.05775726  0.04409219  0.00715972 -0.04460014
   0.09351131  0.20420565 -0.07320229 -0.12871192  0.11155196 -0.14925164
  -0.03458314  0.07712828  0.03806236  0.17127015 -0.14849432 -0.05623256
  -0.1121769  -0.02197258]]

7
[[ 8.55909288e-02  8.23994633e-03 -3.86915244e-02  1.54170943e-02
   1.65897489e-01  5.95633723e-02 -9.25718173e-02  2.48207413e-02
  -1.67652547e-01  1.47562072e-01  1.11502923e-01 -4.07473110e-02
   8.15840531e-03  6.53619468e-02 -1.14362717e-01 -2.77301967e-02
   1.15469843e-01  7.00807497e-02 -5.84432855e-02 -1.00727029e-01
  -7.31224567e-02 -7.90716261e-02  9.24728662e-02 -6.03385568e-02
  -1.23364359e-01  1.29954427e-01  1.88167080e-01  4.85956557e-02
   7.36916065e-02 -9.45381001e-02  1.34815723e-01  8.40811878e-02
   1.22464702e-01 -4.10439074e-02 -2.10569397e-01  8.26804563e-02
  -1.59800559e-01  7.68395215e-02  4.84026559e-02 -5.27111739e-02
   1.58874914e-01 -1.14698801e-02 -7.77634978e-02  4.04179215e-01
  -2.93177739e-02 -2.77198464e-01  9.53527763e-02  1.37391975e-02
   2.97709834e-02 -5.35346521e-03 -8.35933015e-02  8.15539360e-02
  -1.35428354e-01 -1.33888200e-01  2.11769138e-02 -2.75432784e-02
   8.58373642e-02  2.38172263e-02  1.83259360e-02  1.11699156e-01
   4.85866480e-02  2.34631464e-01 -1.33662134e-01 -1.35894209e-01
  -5.40469366e-04 -1.62247404e-01 -1.12020597e-01  7.03570247e-02
   1.48888743e-02 -1.84901245e-03 -9.28412005e-02 -3.02039683e-02
  -2.80047115e-02 -1.23201519e-01 -1.40834138e-01 -1.55667290e-01
   2.98906658e-02  7.52969161e-02  1.11750834e-01  1.34190589e-01]
 [-1.98848024e-01 -4.09684554e-02 -8.89465138e-02 -6.07968271e-02
   1.96721986e-01 -2.41513491e-01 -9.88774002e-02  5.34087047e-02
  -2.37703999e-03  3.64215784e-02  5.38831297e-03 -4.13371250e-02
  -2.44330898e-01  5.09839393e-02 -1.27357617e-01  2.33545229e-01
  -2.78532822e-02  1.76030681e-01 -1.14305206e-01  5.31784147e-02
  -2.06171468e-01  1.02757052e-01 -5.08070216e-02  3.84107381e-02
   1.75917819e-01 -9.33246538e-02  1.67937770e-01 -8.77294391e-02
   5.19544780e-02  6.31371653e-03  7.24538639e-02 -7.81417564e-02
  -1.25382945e-01 -1.24388258e-03 -8.75285566e-02  1.56701192e-01
  -1.37549207e-01 -4.82541323e-02  1.13409668e-01 -4.27365713e-02
   2.99401343e-01  1.85436338e-01 -2.87378505e-02 -1.02323748e-01
  -8.25072080e-03 -1.34712964e-01  4.95931208e-02  5.25051095e-02
  -1.93636138e-02  4.71794344e-02 -1.69478208e-01 -7.74621498e-03
   2.17510369e-02 -6.22578487e-02  5.25485165e-02  2.99595837e-02
  -7.54357055e-02 -1.68626651e-01 -1.50271595e-01 -3.59437987e-02
  -1.43706009e-01 -7.57447183e-02  1.09198868e-01  2.81194467e-02
   2.66545713e-02 -1.93194091e-01 -4.13269028e-02 -4.10768436e-03
  -1.01730116e-01 -8.77730325e-02 -2.72286385e-02  2.84548532e-02
  -1.27261430e-02  1.01631179e-01  1.91290006e-01  6.27294555e-02
   7.82269537e-02 -8.66209120e-02  3.97107229e-02 -4.74305861e-02]
 [ 9.66963619e-02 -5.71634360e-02 -1.03463359e-01 -5.10789789e-02
  -4.46249619e-02 -1.03016734e-01  1.14122532e-01  6.13710694e-02
  -1.05694942e-01  1.81574330e-01  9.95228961e-02  4.51591145e-03
   1.11200046e-02  6.86050877e-02 -1.79543346e-01 -1.87020615e-01
  -1.93605982e-02 -6.20618053e-02 -2.49693349e-01  6.77627921e-02
  -1.54511839e-01 -1.22529708e-01 -9.62990299e-02  5.21628335e-02
   4.36734259e-02  7.25239590e-02  2.76294917e-01  1.37612045e-01
  -5.06126508e-02 -9.54407677e-02 -4.81154099e-02  5.81321754e-02
   2.30605289e-01 -1.98072065e-02 -5.41581947e-04 -1.12965554e-02
  -1.35168117e-02  1.05026357e-01  2.44912490e-01  5.55633791e-02
   2.00102970e-01  2.05090065e-02 -5.82806133e-02  8.65127444e-02
   7.76941106e-02 -2.69801822e-02  3.70929192e-04 -1.53917819e-02
  -7.65009597e-02 -6.29945770e-02  1.28854617e-01  1.20491810e-01
   1.39853721e-02 -2.24583857e-02 -3.81682590e-02  1.75974891e-01
   9.19027999e-02 -1.21508732e-01 -9.01775882e-02 -3.45425494e-02
   1.69016451e-01  2.69129965e-03 -9.78071466e-02  9.43230838e-02
   8.56919587e-02 -3.46704908e-02  1.20515421e-01 -9.01525170e-02
   2.07063839e-01 -2.26951148e-02  1.24640115e-01  1.49027810e-01
   2.70251960e-01 -8.32139552e-02  1.51942670e-01 -9.31696221e-03
   7.68153071e-02 -6.72304854e-02  9.98229906e-02  2.99149621e-02]
 [ 3.85478623e-02 -1.58628505e-02 -3.32533903e-02  3.21213119e-02
  -1.19741693e-01 -6.57443926e-02 -8.49191919e-02  3.12205069e-02
  -1.00893483e-01 -9.03628021e-03  1.63291097e-01 -2.63237357e-01
  -1.12366565e-01  1.57919630e-01  7.43687600e-02  4.93387841e-02
  -6.69539347e-02  3.32754627e-02  1.75889879e-01  2.80493144e-02
  -6.71884716e-02  4.78066644e-03 -3.07328720e-02 -2.29655311e-01
  -2.45834798e-01  1.20678879e-01 -7.70887583e-02 -2.74455585e-02
   1.45707913e-02  1.52489558e-01 -7.52874687e-02  2.40162224e-01
   4.38426621e-02 -7.56262168e-02 -3.67244631e-02  2.28365157e-02
  -2.37840593e-01  1.95036501e-01 -1.34556415e-02  5.65495826e-02
   5.09165339e-02  1.07171528e-01 -6.44711629e-02  1.12308539e-01
  -8.76261592e-02  1.88576132e-01  9.46848944e-04 -1.63369849e-01
   1.12413511e-01 -2.25759104e-01  1.80621028e-01 -2.37671789e-02
  -2.29609936e-01  1.12211831e-01 -7.34120086e-02  2.11689007e-02
  -3.48067246e-02 -9.20037329e-02  1.73041597e-02  4.63504717e-02
  -3.29879783e-02  3.36622931e-02 -1.33621648e-01 -2.70944573e-02
   1.68304831e-01 -2.89977565e-02  7.85075314e-03 -7.38917887e-02
  -2.22327989e-02  3.75077911e-02  5.79672903e-02  1.31460920e-01
   6.90312013e-02 -8.96006599e-02 -1.30778730e-01  9.12323501e-03
   2.21181288e-01 -2.72999685e-02  7.14165494e-02  4.85305563e-02]
 [-5.75921200e-02  6.05734624e-02  1.08224541e-01  7.58069158e-02
  -3.24614309e-02 -2.17146035e-02 -4.78402264e-02  3.36386293e-01
   7.92402476e-02  9.22024250e-03  1.96181104e-01 -5.73679246e-02
   3.81553895e-04  2.77793676e-01 -9.02251899e-03 -1.98398739e-01
   1.03527904e-01 -2.69408543e-02  3.16955708e-02  2.57016011e-02
  -1.89602703e-01  4.62559797e-02  1.33551620e-02 -1.00115880e-01
  -1.35937810e-01  7.05092326e-02 -3.32212150e-02  9.09414366e-02
   2.06226140e-01  4.27837335e-02  5.34213148e-02  7.65340626e-02
   1.23854056e-01  1.29608084e-02 -6.84257448e-02 -1.37116751e-02
  -1.68377664e-02  6.22522347e-02  2.02472031e-01 -9.71622244e-02
  -7.01379254e-02  2.10175499e-01 -2.44154587e-01 -9.39810723e-02
  -8.19520000e-03  5.34294322e-02  1.87508781e-02 -2.64638122e-02
  -8.73880535e-02 -1.49481848e-01  1.81609869e-01  4.79856990e-02
  -4.70160581e-02 -1.05020627e-02  6.39741123e-02 -1.56534035e-02
  -1.42548298e-02  1.22424411e-02  1.48584351e-01  1.18785361e-02
   2.19081510e-02  1.34716794e-01 -6.27805144e-02  7.30905086e-02
  -2.01163217e-02  1.80261716e-01 -2.15586298e-03  1.28715590e-01
  -1.12143159e-01  5.81787601e-02  1.24322318e-01 -1.63794205e-01
  -1.37906391e-02  1.04713151e-02 -1.42301261e-01 -7.79722109e-02
   2.96603441e-01  2.39766538e-02  3.86966132e-02 -5.70259392e-02]
 [-1.92330644e-01  2.02468187e-01 -4.92334887e-02  2.05565244e-01
  -1.02805309e-01  3.34238559e-02  1.83873266e-01 -4.56914194e-02
   1.57284111e-01 -3.47853638e-02 -1.14405109e-02  1.05575807e-01
  -1.82443872e-01 -2.51241446e-01 -1.25175044e-01  1.42836332e-01
  -6.89480156e-02 -5.68748787e-02  4.02579382e-02 -3.52373440e-03
  -1.82964996e-01  2.07623348e-01 -1.20797053e-01  1.35134578e-01
  -1.15689315e-01 -1.89163946e-02  1.94070637e-02  1.53090507e-01
  -9.04096812e-02 -5.68609200e-02 -8.08729976e-02  1.01485401e-01
   2.10387837e-02 -1.20043606e-01 -2.50345439e-01 -4.38027568e-02
   2.74697933e-02 -1.82132438e-01  1.60857439e-01 -8.24016184e-02
  -7.55357072e-02  5.44412015e-03 -1.20047569e-01 -2.84332372e-02
   1.93635866e-01 -1.09323844e-01 -2.68992856e-02 -1.54793765e-02
   2.59039626e-02  1.14774399e-01 -2.45150570e-02  2.28235032e-02
   3.54586393e-02 -1.62783653e-01 -3.33438963e-02 -4.11900394e-02
   4.07081135e-02 -4.15974110e-02  1.55803803e-02  6.89549744e-02
  -5.65667562e-02 -7.04842061e-02  2.00904682e-01 -1.57108575e-01
   3.88935246e-02 -6.02030531e-02 -3.72520313e-02 -5.90695105e-02
   5.18789701e-02  2.62615327e-02  1.62576750e-01  6.16537817e-02
  -1.18230591e-02 -8.76743421e-02  1.45972252e-01  8.14559832e-02
   9.22660902e-02 -1.00664245e-02  8.78740624e-02  1.86875477e-01]
 [-4.11975160e-02  2.97549754e-01  1.23161245e-02 -2.79170033e-02
   8.16534907e-02 -1.18629642e-01 -7.79023394e-02  5.83051369e-02
   2.03868985e-01 -1.95685357e-01  3.16552110e-02  1.69127464e-01
  -1.71669349e-01  1.67739004e-01 -1.95215922e-02  2.50150319e-02
   9.89585444e-02  1.02327526e-01  2.14274988e-01 -9.43175107e-02
  -1.42399386e-01  2.40250193e-02  4.61705960e-02 -1.09894082e-01
  -1.17994938e-03 -1.06286444e-01 -2.24219896e-02  4.09412645e-02
  -3.79915871e-02  3.62089165e-02 -4.02149782e-02 -6.13757111e-02
  -2.71918207e-01  4.95773442e-02  2.56755855e-02 -1.35575412e-02
  -2.06804015e-02 -1.39776887e-02 -1.66701466e-01 -1.15639254e-01
   7.06805214e-02  2.58979946e-02 -2.58951962e-01 -2.10399345e-01
   5.10479063e-02  1.14998162e-01  6.29436672e-02  6.13114648e-02
   1.10421278e-01 -7.85444081e-02  1.04369834e-01  4.89821546e-02
  -3.75747979e-02  8.01845118e-02  8.11674371e-02  2.56270140e-01
  -3.47761139e-02  2.95284223e-02 -1.52634472e-01 -5.42687327e-02
  -3.80015448e-02 -1.42540783e-01 -4.37929891e-02  1.08405631e-02
   1.23826303e-01 -9.51893181e-02 -1.48477554e-01 -1.34035051e-01
  -8.51974264e-02 -4.74271514e-02 -4.61914763e-02  1.24760628e-01
  -3.98570038e-02  8.34969245e-03 -2.32373122e-02 -1.61865160e-01
   1.07253328e-01  2.33904589e-02  7.76626822e-03  1.52421504e-01]]

**Comment by dkirman-re** [comment]
Not sure if `Top2Vec2` class works in this case, but calling `top2vec_model.get_num_topics(reduced=True)` should give you the number of topics you're looking for. 
You'll notice in the API that passing a `True` argument value into the `reduced` parameter will yield hierarchical-based results in most of the getter functions.

**Comment by waguken** [comment]
It was really helpful. Thank you.
