### ISSUE TITLE
ValueError: numpy.ndarray size changed

### ISSUE THREAD

**Issue by nicolaiberk** [ddangelov/Top2Vec#320]
Hi!

First off, thank you for buidling this amazing package!

Currently trying to run Top2Vec. Upon calling:
```
from top2vec import Top2Vec
```

I get:

```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

using `Python 3.8.10` in Colab.

This seems to be the case for other packages using HDBSCAN, too: https://github.com/MaartenGr/BERTopic/issues/392

Hope this helps.

Best,
Nico

**Comment by GranamyrBR** [comment]
Same here.  I suspect the Numpy, Gensim, Pandas, Top2Vec packages compatibilies.

**Comment by ddangelov** [comment]
If you run:

```
!pip uninstall numpy -y
!pip install numpy==1.23.5
```

then restart runtime it should work in Colab.

**Comment by MereOsman** [comment]
Hi, i fixed this error with

```
pip install numpy==1.22.1
```

my version of top2vec for this is 1.0.28

Hopefully that works for you too but if you get similar issues with other packages maybe check what versions of them were released at the time of which the version of top2vec you are using was released, that should give you what package versions you need for it to run hopefully.

**Comment by nicolaiberk** [comment]
Thank you for the quick response, guess I forgot to restart...
