### ISSUE TITLE
Top2Vec for corpus larger than memory 

### ISSUE THREAD

**Issue by mohsin-ashraf** [ddangelov/Top2Vec#33]
Is there any way of training the top2vec model on a corpus which you cannot fit in memory? For example, I have a corpus of 10 million documents and it is about 500GB, and I have RAM = 128GB, how would I get the top2vec model trained on this dataset?

**Comment by ddangelov** [comment]
If you cannot read your documents into memory to pre-process them there currently isn't a way to stream them. That should be possible though.
