### ISSUE TITLE
Finding all topics a document is related to?

### ISSUE THREAD

**Issue by kmankinen** [ddangelov/Top2Vec#34]
Hello! First, thanks a lot, this is a really nice package to play with! Is there a clean and easy way to get all topics a document is associated to? It can ofc be achieved by iterating over all topics by `search_documents_by_topic`. Perhaps I overlooked some methods?

Edit: Giving a second thought. Maybe it is not even possible that a document belongs to more than one topic.

**Comment by ddangelov** [comment]
There will be a method added to do this sometime this week!

**Comment by hetryn** [comment]
Can't wait to try to feature 👍
