### ISSUE TITLE
Bug with topic_words and add_documents()

### ISSUE THREAD

**Issue by SinyTim** [ddangelov/Top2Vec#35]
Hi!
topic_words (and topic_words_reduced as well) is not reordered when add_documents() is called with a large number of documents.
Probably the problem with [this method](https://github.com/ddangelov/Top2Vec/blob/b82de5a4b91b7eb04eaf275356164b91991c80aa/top2vec/Top2Vec.py#L296).
I solved it in my code (without editing you package) in the following way:

```
index_start = model.documents.shape[0]
doc_top_reduced_old = model.doc_top_reduced[:index_start]

model.add_documents(documents)

doc_top_reduced_new = model.doc_top_reduced[:index_start]
topic_new_to_old = dict(zip(doc_top_reduced_new, doc_top_reduced_old))
index = [topic_new_to_old[i] for i in range(len(topic_new_to_old))]
model.topic_words_reduced = model.topic_words_reduced[index]
```

By the way, Great tool! :)

**Comment by ddangelov** [comment]
Thank you for pointing this out, I have found the problem and it will be fixed shortly! :)

**Comment by ddangelov** [comment]
Fixed!
