### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by apoorvasahu** [ddangelov/Top2Vec#36]
RuntimeError: you must first build vocabulary before training the model

After document(list of string) is passed the respective runtime error arrives. 
Also top2vec is imported.

**Comment by apoorvasahu** [comment]
Let me know how to fix this.

**Comment by ddangelov** [comment]
This is an environment error. Try restarting the kernel if using Jupyter. If that doesn't work create a new environment with a fresh top2vec install.

**Comment by apoorvasahu** [comment]
![Screenshot from 2020-10-06 07-25-39](https://user-images.githubusercontent.com/39028318/95150183-43988780-07a5-11eb-83d4-79a9b1ca18bc.png)

As u can see the sample dataset[news group] is working. There was no error of  "RuntimeError: you must first build vocabulary before training the model". 

I restarted the kernel several times.

**Comment by ddangelov** [comment]
Try creating a new environment with a fresh top2vec install. This should not be happening.

**Comment by apoorvasahu** [comment]
from top2vec import Top2Vec
record=[('@gmisrag @manas_saloi Read all? :)',), ('I want to take this opportunity and thank the people who have been there with me on Day 0 of building this —… https://t.co/yNSDLs65BS',)]
# print (str(record)) 
res = [''.join(i) for i in record] 
# print (str(res)) 
model1 = Top2Vec(documents=res, speed="learn", workers=8)


So this is my code. 
I created an environment and installed Top2vec still the same error. 
What wrong am I doing here?

**Comment by ddangelov** [comment]
First you need **way** more documents. Second try reducing `min_count` to 1, it is set to 50 by default. All words with total frequency lower than this are ignored. This is likely the main source of your error.

**Comment by nateGeorge** [comment]
I had the same error and the issue was not enough documents.

**Comment by jun3599** [comment]
The solution to the issue was simpler than expected. After installing top2vec and restarting the kernel, the problem disappeared!
