### ISSUE TITLE
Unable to run the example provided.

### ISSUE THREAD

**Issue by pidugusundeep** [ddangelov/Top2Vec#37]
```
from top2vec import Top2Vec
from sklearn.datasets import fetch_20newsgroups

newsgroups = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))

model = Top2Vec(documents=newsgroups.data, speed="learn", workers=8)
```

Error:
```
Traceback (most recent call last):
  File "checkThis.py", line 13, in <module>
    model = Top2Vec(documents=allSents, speed="learn", workers=8)
  File "/workspace/Top2Vec/top2vec/Top2Vec.py", line 234, in __init__
    self._create_topic_vectors(cluster.labels_)
  File "/workspace/Top2Vec/top2vec/Top2Vec.py", line 260, in _create_topic_vectors
    self.topic_vectors = np.vstack([self.model.docvecs.vectors_docs[np.where(cluster_labels == label)[0]]
  File "<__array_function__ internals>", line 5, in vstack
  File "/workspace/.pip-modules/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```
My NumPy version : '1.19.0'

**Comment by ddangelov** [comment]
what is the variable `allSents`?

**Comment by pidugusundeep** [comment]
That's the same `allSents = newsgroups.data`

**Comment by ddangelov** [comment]
Try creating a fresh environment and pip installing top2vec.

**Comment by pidugusundeep** [comment]
That worked, when I used `newsgroups.data` but when I use plain sentences of length 300(list) it again shows me the error curious to know if there is any minimum requirement of sentences that should be used for documents?

**Comment by ddangelov** [comment]
I am not sure what the exact number is but 1000+ is usually good. I will look at setting a threshold in the future. Also if you are using fewer documents, try setting `min_count` to 1. That could also help. `min_count` ignores all words with total frequency lower than this. For smaller corpora a smaller `min_count` will be necessary.
