### ISSUE TITLE
Any pretrained model release?

### ISSUE THREAD

**Issue by riven314** [ddangelov/Top2Vec#40]
Right now we need to train the Top2Vec model from a large corpus, but in many problems we only have small corpus
Would you plan to release any pre-trained Top2Vec models? I believe it could greatly benefit more users especially those who are facing small data issue

**Comment by ddangelov** [comment]
There is a long term plan to introduce pre-trained embedding methods that don't require lots of data. A pre-trained model of the current version of Top2Vec is also a possibility. So it is definitely something that will be coming in the future.

**Comment by riven314** [comment]
@ddangelov 
awesome! is there any tutorial on some extended use cases of those pretrained model?
e.g. 
- find the topic(s) for each sample from user's data set
