### ISSUE TITLE
Topics empty or only contains stop words

### ISSUE THREAD

**Issue by chhaosh** [ddangelov/Top2Vec#41]
I set documents to around 1000 strings each is a subject of research paper (less than 10 words), but model generates topics either only contains stop words or empty, anything I may did wrong? 
![image](https://user-images.githubusercontent.com/34704048/95550621-0bb85c80-09be-11eb-8f9b-adf8e08f3988.png)

**Comment by ddangelov** [comment]
Without seeing the actual abstracts it is hard to say. My guess is that although you have 1000 strings, they are **very** short. Top2Vec has to learn both word and document vectors which it is probably unable to do with so little data. There may be a pre-trained model in the future and perhaps an option for other embedding methods that do not require lots of data. For the time being using more documents that are long which allow the model to learn vectors will be necessary.
