### ISSUE TITLE
Is it possible to visualise the trained top2vec model?

### ISSUE THREAD

**Issue by PiyushKyushu** [ddangelov/Top2Vec#42]
Can you please add code lines for umap and hdbscan visualization? 

I am trying the below code for umap but not sure what should I put in fit_transform(?).

```
import umap
import time
umap_embeddings = umap.UMAP(n_neighbors=15,
                            n_components=5,
                            min_dist=0.0,
                            metric='cosine',
                            random_state=42).fit_transform(?)
```

**Comment by PiyushKyushu** [comment]
I trained the top2vec model on my own dataset using deep-learn option. Top2Vec produces 320 topics. Now I want to visualize this. I tried using umap (above code) and hdbscan but facing issues. 
Please help me understand ways o visualize top2vec model.

**Comment by ddangelov** [comment]
What exactly are you looking to visualize?

**Comment by PiyushKyushu** [comment]
Just like in LDA and NMF topic models, all Topics can be visualized using multidimensional scaling  (MDS), t-sne, pyLDAvis, or any other visualizations. Similarly, I was wondering if there is any visualization model that can be used to visualize all topics that the top2vec model produces?

**Comment by ddangelov** [comment]
You can use the `top2vec.topic_vectors` which will be 300 dimensional and reduce them to 2D using umap. The `top2vec.topic_words` will be the descriptions of each topic vector, the indexes will match.
