### ISSUE TITLE
"embedding_model" parameter in Top2Vec is unrecognized

### ISSUE THREAD

**Issue by Prashant118** [ddangelov/Top2Vec#44]
In code documentation it is mentioned that we can use pretrained model using _embedding_model_ but it is not recognized. I have updated the library as well

**Comment by ddangelov** [comment]
Please show the exact code you ran as well as the error.

**Comment by ddangelov** [comment]
Closing due to lack of response and clarity of question.

**Comment by Prashant118** [comment]
![image](https://user-images.githubusercontent.com/2352213/96371598-fd1d3280-117f-11eb-9929-cb043d04dfc0.png)

**Comment by ddangelov** [comment]
Try `pip install top2vec==1.0.15`, it looks like you have an older version.

**Comment by Prashant118** [comment]
I am getting the below error after trying to install top2vec==1.0.15. I tried few solutions from stackoverflow but it is not working. Still exploring but if you are familiar with this error then please let me know
_ERROR: Could not find a version that satisfies the requirement tensorflow-text (from top2vec==1.0.15) (from versions: none)
ERROR: No matching distribution found for tensorflow-text (from top2vec==1.0.15)_

**Comment by Prashant118** [comment]
No solutions worked. It looks like tensorflow-text can't be installed on windows system. Is there any workaround?

**Comment by ddangelov** [comment]
It sounds like tensorflow-text isn't available for windows. I could make the embedding models a separate install dependancy. In which case you would potentially be able to use the `distiluse-base-multilingual-cased` sentence transformer and `doc2vec` but you still would not be able to use the universal sentence encoder.

**Comment by ivanviragine** [comment]
> No solutions worked. It looks like tensorflow-text can't be installed on windows system. Is there any workaround?

Try using it through WSL and vs code.

**Comment by ddangelov** [comment]
Issue should be fixed, try version 1.0.16.
