### ISSUE TITLE
Model Inference

### ISSUE THREAD

**Issue by federicoBetti44** [ddangelov/Top2Vec#45]
Thanks a lot for your word, I think you're building something great!

Just a few questions:
Given an unseen document, it is possible to know which are the topic related to it? 
It is possible to assign a name to a topic to retrieve just its name instead of the main words?
Using the function add_documents is like "fine-tuning" the model?

Thanks

**Comment by ddangelov** [comment]
The current best way to get the topic of an unseen document is to add it to the model with `add_documents` then use the `get_documents_topics` which will give you its topic number and corresponding topic words. There will likely be an `infer_topic` method in the future which does both of those. 

Topics are assigned numbers, and they have corresponding words that describe them.

Top2Vec is used when you have a large collection of documents that you want to extract topics from. After training a model on a set of documents `add_documents` allows you to add more document to the trained model.
