### ISSUE TITLE
Get documents id

### ISSUE THREAD

**Issue by hetryn** [ddangelov/Top2Vec#47]
After doing an `add_documents` for a list of documents, I want to do a `get_documents_topic`. However, `get_documents_topic` requires me to input `doc_id` as its argument. Without giving the documents an id in the beginning, is there an easier way to search document id? Such as a `get_documents_id` function?

Something like 
```
def get_document_id(self, document):
   if self.documents is not None:
        document_id = self.documents.tolist().index(document)
   return document_id
```

**Comment by ddangelov** [comment]
`add_documents` could perhaps return the ids. Also there will be a `infer_topic` option soon, that will do what I believe you are looking for, without having to add the documents.
