### ISSUE TITLE
len(self.documents) != len(self.doc_top)

### ISSUE THREAD

**Issue by hetryn** [ddangelov/Top2Vec#49]
Hey, I've been playing around with the new stuff. Really exciting.

One question though. Under the method `get_document_topics`, I added print statements to look at the stuffs as shown in the snippet below.

<img width="438" alt="Screenshot 2020-10-20 at 1 06 39 AM" src="https://user-images.githubusercontent.com/24973977/96488449-99befd80-1270-11eb-87ae-6bbcddf43c18.png">

The results are shown in the snippet below here. I'm trying to understand why are the two lengths `len(documents)` and `len(doc_top)` or len(doc_top_reduced)` unequal?

![Screenshot 2020-10-20 at 1 03 17 AM](https://user-images.githubusercontent.com/24973977/96488236-3cc34780-1270-11eb-98c1-28eb55c552da.png)

Down here, I have hierarchically reduced the number of topics to 10.

**Comment by ddangelov** [comment]
Which `embedding_model` did you use? Did you `add_documents` and/or `delete_documents` from the model?

**Comment by hetryn** [comment]
i used doc2vec. Have not used `add_documents` and/or `delete_documents`. My original document size is 10170324 which `len(documents)` is correct. Just wondering why `doc_top` and `doc_top_reduced` has a shorter length.

**Comment by ddangelov** [comment]
Which version of top2vec do you have currently? did you have `use_corpus_file` set to True?

**Comment by hetryn** [comment]
i'm using v1.0.13. Yup, `use_corpus_file` is set to `True`.

**Comment by ddangelov** [comment]
There was a bug in that version with `use_corpus_file` set to `True`. The best solution is `pip install top2vec==1.0.15`, which is the current version. The other option is to set `use_corpus_file` to `False`.

**Comment by hetryn** [comment]
I think it's because the number of output vectors from doc2vec is different from the number of input documents.

**Comment by ddangelov** [comment]
When using `use_corpus_file` a temporary file is created and the documents are written to that temporary file, doc2vec reads from it during training. There is a bug however, that should now be fixed, that leads to fewer documents being written to the temporary file resulting in a lesser amount of document vectors than documents.

**Comment by hetryn** [comment]
yup latest version will have the length of `doc_id` and `documents` aligned.
