### ISSUE TITLE
Fasttext integration

### ISSUE THREAD

**Issue by shimonhaf** [ddangelov/Top2Vec#50]
First, thanks for great work.
There is some prevention to integrate a fasttext language model? 
I think it may work better than Doc2Vec for some corpuses.

**Comment by ddangelov** [comment]
Doc2Vec is a document embedding technique, Fasttext is a word embedding technique. Top2Vec requires document embedding. Top2Vec has several options for `embedding_model` that should give you what you are looking for.

**Comment by shimonhaf** [comment]
Actually fasttext can be used as a document embedding model.
