### ISSUE TITLE
[feature-request] Pretrained vectors for w2v and "universal-sentence-encoder-multilingual-large" option

### ISSUE THREAD

**Issue by ivanviragine** [ddangelov/Top2Vec#52]
Hi!

First of all: great work! I'm testing this approach with great results!
I would like to suggest an option to use pretrained word2vec embeddings using the embedding_model_path param, so that we can pass customized embeddings to our model.
Also, I would like to know if universal-sentence-encoder-multilingual-large model was tested or will be an option in the future.

**Comment by ddangelov** [comment]
Thank you!

Using `doc2vec` as the `embedding_model` will learn word and document embeddings that are specific to your dataset. This works very well with datasets that are large enough. There may be a an option to learn document embeddings with a pre-trained word2vec model but that will require some work as doc2vec is not currently implemented to work that way. 

The `universal-sentence-encoder-multilingual-large` and `universal-sentence-encoder-large` will both be tested and added if they produce good results.

**Comment by Jeetkarsh** [comment]
Do we have support to use other embedding model, I don't see any option of specifying model at the time of training.
