### ISSUE TITLE
conflicting dependecy versions

### ISSUE THREAD

**Issue by nxhoehing** [ddangelov/Top2Vec#54]
Hi,

I am getting this Error when running pip install top2vec:
ERROR: numba 0.51.2 has requirement llvmlite<0.35,>=0.34.0.dev0, but you'll have llvmlite 0.31.0 which is incompatible.

Running this example then fails
![Bildschirmfoto 2020-10-28 um 11 39 41](https://user-images.githubusercontent.com/70569873/97425652-b0b9bb80-1912-11eb-9df7-164015a324a3.png)

Do you know a way to fix this? Thanks a lot in advance!

**Comment by ddangelov** [comment]
I would suggest creating a fresh environment and installing top2vec there.
