### ISSUE TITLE
How to make topics more distinguishable?

### ISSUE THREAD

**Issue by YukunYangNPF** [ddangelov/Top2Vec#55]
Hi there. I'm trying to use this module on some tweets. I found the word clouds generating from each topic almost has the same elements. 

Is there any way to make each topic more distinguishable from the others?

Thanks in advance.

**Comment by ddangelov** [comment]
Can you give some more detail? How many tweets are you running it on?

**Comment by YukunYangNPF** [comment]
Oh... I think I figured out something. The situation happened when I used the Universal Sentence Encoder but not the default Doc2Vec.

I'm running on 50k tweets. The situation is like every topic's top words showing up in the word cloud is almost the same, with all top words very similar.
