### ISSUE TITLE
[feature request] Is there a simple way to extract the vocabulary learned? 

### ISSUE THREAD

**Issue by sanchez5674** [ddangelov/Top2Vec#57]
Hi, 

Thanks for the great work. 

What would be the simplest way to extract the learned vocabulary from the model? I would like to avoid the error regarding the word not being known by the model. 

Carlos

**Comment by ddangelov** [comment]
If you are using `doc2vec` for `embedding_model` then `top2vec.model.wv.vocab` otherwise it is `top2vec.vocab`.
