### ISSUE TITLE
[Installation Issue] Unable to install dependencies

### ISSUE THREAD

**Issue by chintanckg** [ddangelov/Top2Vec#58]
I have windows 10, python 3.6, x64

I get following error when I do 'pip install top2vec'

ERROR: Could not find a version that satisfies the requirement tensorflow-text (from top2vec) (from versions: none)
ERROR: No matching distribution found for tensorflow-text (from top2vec)

**Comment by ddangelov** [comment]
My understanding is that currently tensorflow-text isn't available for windows, see #44 for more details. 

There is a fix coming that will make this dependancy optional. This will allow you to install `top2vec` but you will not be able to use the `universal-sentence-encoder` options.
