### ISSUE TITLE
Measurement of the model

### ISSUE THREAD

**Issue by fajarmuslim** [ddangelov/Top2Vec#60]
Hi all. This repo is absolutely great. There are very great topic modeling. but, sometimes we need a number to verify the quality of topic modeling model. In the original paper, there is mentioned about **performance measure using topic information gain**. How is it calculate and compare with other approach? I don't see anything about the calculation of information gain in this repo. *cmiiw

**Comment by ddangelov** [comment]
Topic information gain may be added or put in a new repo in the future, but unfortunately it is currently not available.

**Comment by fajarmuslim** [comment]
Thanks a lot !!
