### ISSUE TITLE
Training on more than 300 million Articles

### ISSUE THREAD

**Issue by arsalan993** [ddangelov/Top2Vec#62]
I have a dataset of more than 300 million articles. Considering the fact that a blog contains a word of size 4.9 characters and on average 700 words.  I expect the dataset to be 1.239TB. 
I have hardware limitations and considering that is it possible that I train the model on a small subset, save that model, and on the next subset, I perform transfer learning and somehow retaining previous knowledge as well.
I will consider using BERT as a base model.

**Comment by ddangelov** [comment]
I would reccomend `doc2vec` or `universal-sentence-encoder-multilingual`.

**Comment by arsalan993** [comment]
But Question is how to perform transfer learning????????????????
