### ISSUE TITLE
Search topics by documents

### ISSUE THREAD

**Issue by LianaN** [ddangelov/Top2Vec#63]
Hi Dimo,
I see that Top2Vec can search documents by topic. Is it possible to do the reverse search? (i.e. search topics by documents).
Thanks.

**Comment by LianaN** [comment]
I've just checked your source code and came up with the following solution that retrieves the topic ID based on a text:

```
model = Top2Vec.load("top2vec.model")

documents = [
   "document text goes here"
]

docs_processed = [model._tokenizer(doc) for doc in documents]

docs_training = [' '.join(doc) for doc in docs_processed]
document_vectors = model._embed_documents(docs_training)

doc_top, doc_dist = model._calculate_documents_topic(model.topic_vectors, document_vectors, dist=True)
```

I think that it would be helpful to expose it as a function `search_topics_by_document`.

**Comment by ddangelov** [comment]
There is a way to get the topics of documents in the model using: https://github.com/ddangelov/Top2Vec/blob/69e98be3b0fed16b27c9d11baecd6aae95262cee/top2vec/Top2Vec.py#L807

If you wanted to get topics of a document (search topics by document) not in the model there currently is no way to do that. However an `infer_topic` method will eventually be added.

**Comment by LianaN** [comment]
Thanks for your feedback, Dimo. If I understand correctly, this method takes IDs of documents, right?
In my case, I need to pass a new text to infer a topic. The new text always contains some words from the training text corpus.
In fact, I applied the code that I shared above and it identified topics quite accurately.
Please let me know if you see any weaknesses with this approach. Thanks.

**Comment by ddangelov** [comment]
Your approach is correct. The `infer_topic` method that takes unseen documents will be added in a future version.

**Comment by arsalan993** [comment]
is there any other way .. where we gave the model a text and it predicts the top 5 models?

For now, I am using word tokens of a particular document and feeding that into the model but problem is that list of tokens may contain a word not present in the vocabulary of word vectors. 
Is there a way where we can ignore or somehow find if a particular word exists in vocabulary or not?

Also, can we perform training at n-gram level like FAST-Text word embedding vectors,  such character or n-gram level embeddings are useful if the spelling is incorrect?

**Comment by abdelatifsd** [comment]
> is there any other way .. where we gave the model a text and it predicts the top 5 models?
> 
> For now, I am using word tokens of a particular document and feeding that into the model but problem is that list of tokens may contain a word not present in the vocabulary of word vectors.
> Is there a way where we can ignore or somehow find if a particular word exists in vocabulary or not?
> 
> Also, can we perform training at n-gram level like FAST-Text word embedding vectors, such character or n-gram level embeddings are useful if the spelling is incorrect?

Hello Arsalan, the model has a "vocab" attribute which returns a list of all the words the model includes. Maybe something like the this could help you out with filtering your list of tokens: [word for word in input_document if word in model.vocab] where the input document is a list of words (your input document split).

**Comment by arnov** [comment]
I've used this, which I think does the right thing, but it might be a bit too slow, since it actually updates the model:

```
model.add_documents([text])
new_doc_id = len(model.documents) - 1
model.get_documents_topics([new_doc_id])
```

**Comment by paulthemagno** [comment]
> I've used this, which I think does the right thing, but it might be a bit too slow, since it actually updates the model:
> 
> ```
> model.add_documents([text])
> new_doc_id = len(model.documents) - 1
> model.get_documents_topics([new_doc_id])
> ```

@ddangelov is @arnov's method correct until the `infer_topic` method isn't available? I'm interested to this theme. Maybe with the delete of the document from the model at the end not to alterate the model.

```python
model.add_documents([text])
new_doc_id = len(model.documents) - 1
model.get_documents_topics([new_doc_id])
model.delete_documents([new_doc_id])
```

**Comment by ddangelov** [comment]
> > I've used this, which I think does the right thing, but it might be a bit too slow, since it actually updates the model:
> > ```
> > model.add_documents([text])
> > new_doc_id = len(model.documents) - 1
> > model.get_documents_topics([new_doc_id])
> > ```
> 
> @ddangelov is @arnov's method correct until the `infer_topic` method isn't available? I'm interested to this theme. Maybe with the delete of the document from the model at the end not to alterate the model.
> 
> ```python
> model.add_documents([text])
> new_doc_id = len(model.documents) - 1
> model.get_documents_topics([new_doc_id])
> model.delete_documents([new_doc_id])
> ```
> 
> Also because I'm interested to the `reduced` parameter which I see is not available in `_calculate_documents_topic` method (I was trying to follow the @LianaN's [approach](https://github.com/ddangelov/Top2Vec/issues/63#issuecomment-721958072)

The above is the correct way of doing it currently. If you want to get the reduced topics of the document you can do the following:

```python
model.get_documents_topics([new_doc_id], reduced=True)
```

**Comment by ddangelov** [comment]
Version 1.0.25 now has a `query_topics` method which should do what you are looking for, although for one document at a time.
