### ISSUE TITLE
An error when running the 20newsgroups example

### ISSUE THREAD

**Issue by wmmxk** [ddangelov/Top2Vec#65]
When I run the 20newsgroups example, I run into this error: ValueError: Buffer has wrong number of dimensions (expected 1, got 2). Traceback of the error is as follows:
 

ValueError                                Traceback (most recent call last)
<ipython-input-3-c7a3da58121e> in <module>
----> 1 model = Top2Vec(documents=newsgroups.data, speed="learn", workers=8)

/mifusion134/XKW/envs/topic2vec/lib/python3.7/site-packages/top2vec/Top2Vec.py in __init__(self, documents, min_count, embedding_model, embedding_model_path, speed, use_corpus_file, document_ids, keep_documents, workers, tokenizer, verbose)
    316         umap_model = umap.UMAP(n_neighbors=15,
    317                                n_components=5,
--> 318                                metric='cosine').fit(self._get_document_vectors())
    319 
    320         # find dense areas of document vectors

/mifusion134/XKW/envs/topic2vec/lib/python3.7/site-packages/umap/umap_.py in fit(self, X, y)
   1450             self._search_graph.data = (self._knn_dists != 0).astype(np.int8)
   1451             self._search_graph = self._search_graph.maximum(
-> 1452                 self._search_graph.transpose()
   1453             ).tocsr()
   1454 

/mifusion134/XKW/envs/topic2vec/lib/python3.7/site-packages/scipy/sparse/lil.py in transpose(self, axes, copy)
    435 
    436     def transpose(self, axes=None, copy=False):
--> 437         return self.tocsr(copy=copy).transpose(axes=axes, copy=False).tolil(copy=False)
    438 
    439     transpose.__doc__ = spmatrix.transpose.__doc__

/mifusion134/XKW/envs/topic2vec/lib/python3.7/site-packages/scipy/sparse/lil.py in tocsr(self, copy)
    460             indptr = np.empty(M + 1, dtype=idx_dtype)
    461             indptr[0] = 0
--> 462             _csparsetools.lil_get_lengths(self.rows, indptr[1:])
    463             np.cumsum(indptr, out=indptr)
    464             nnz = indptr[-1]

_csparsetools.pyx in scipy.sparse._csparsetools.lil_get_lengths()

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

Is there anyone who run into the same error?

**Comment by wmmxk** [comment]
The error points to umap.UMAP, it might be because the version of the umap package I installed is not correct or the code fails before running umap.UMAP. Any ideas will be appreciated.

**Comment by ddangelov** [comment]
I would recommend creating a fresh environment with a fresh `pip install top2vec`.

**Comment by wmmxk** [comment]
Thanks for your reply. I create a new environment then installed the packages in the requirements.txt file. The version of the default installed umap is not correct. After I intall umap==0.3.10. It works now.

**Comment by wmmxk** [comment]
One thing to add, the requirements.txt is not a exhaustive list of packages needed by this project. Here is a list of all the packages I am using now.
absl-py==0.9.0
astunparse==1.6.3
attrs==20.3.0
backcall==0.2.0
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
cycler==0.10.0
Cython==0.29.21
dataclasses==0.7
decorator==4.4.2
dill==0.3.2
filelock==3.0.12
future==0.18.2
gast==0.3.3
gensim==3.8.3
google-auth==1.20.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
googleapis-common-protos==1.52.0
grpcio==1.31.0
h5py==2.10.0
hdbscan==0.8.26
idna==2.10
imageio==2.9.0
importlib-metadata==2.0.0
ipykernel==5.3.4
ipython==7.16.1
ipython-genutils==0.2.0
jedi==0.17.2
joblib==0.17.0
jupyter-client==6.1.7
jupyter-core==4.6.3
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
lime==0.2.0.1
llvmlite==0.34.0
Markdown==3.2.2
matplotlib==3.3.2
networkx==2.5
nltk==3.5
numba==0.51.2
numpy==1.18.5
oauthlib==3.1.0
opt-einsum==3.3.0
packaging==20.4
pandas==1.1.4
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.0.1
portalocker==2.0.0
promise==2.3
prompt-toolkit==3.0.8
protobuf==3.13.0
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.7.1
pynndescent==0.5.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytorch-lightning==0.8.5
pytz==2020.4
PyWavelets==1.1.1
pyzmq==19.0.2
regex==2020.7.14
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
sacrebleu==1.4.13
sacremoses==0.0.43
scikit-image==0.17.2
scikit-learn==0.23.2
scipy==1.4.1
sentence-transformers==0.3.8
sentencepiece==0.1.91
six==1.15.0
smart-open==3.0.0
svgwrite==1.4
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.0
tensorflow-datasets==3.2.1
tensorflow-estimator==2.3.0
tensorflow-hub==0.10.0
tensorflow-metadata==0.23.0
tensorflow-text==2.3.0
termcolor==1.1.0
threadpoolctl==2.1.0
tifffile==2020.9.3
tokenizers==0.8.1rc2
top2vec==1.0.15
torch==1.7.0
tornado==6.0.4
tqdm==4.51.0
traitlets==4.3.3
transformers==3.3.1
Tree==0.2.4
typing-extensions==3.7.4.3
umap-learn==0.3.10
urllib3==1.25.11
wcwidth==0.2.5
Werkzeug==1.0.1
wordcloud==1.8.0
wrapt==1.12.1
zipp==3.4.0

**Comment by wmmxk** [comment]
One more thing, the error I run into when the version of umap package is not correct is like [this](https://stackoverflow.com/questions/57242208/how-to-resolve-the-error-module-umap-has-no-attribute-umap-i-tried-installi)
