### ISSUE TITLE
Is there a limit to the length of each document in a corpus

### ISSUE THREAD

**Issue by wmmxk** [ddangelov/Top2Vec#66]
In the readme.md file, it is said. "Create jointly embedded document and word vectors using Doc2Vec or Universal Sentence Encoder or BERT Sentence Transformer."

In a Doc2Vec model, the length of the a doc appears not to make a difference because each doc is represented by an id when training a model. 

Whereas, the length of an input doc to a transformer has to be less than 512.

Am I right?

**Comment by ddangelov** [comment]
Doc2Vec and Universal Sentence Encoder do not have document length limits. The BERT Sentence Transformer truncates documents to the first 512 characters automatically. More info [here](https://www.sbert.net/docs/pretrained_models.html).

**Comment by uoneway** [comment]
As i know... the universial sentence encoder has two version, one is CNN based and the othe one is transformer based. And the former one gets input to 256 tokens and latter one gets input to 100 token. Isn't it?

**Comment by ddangelov** [comment]
The first universal sentence encoder option uses a deep averaging network(DAN), it doesn't have a token limit. See more info [here](https://tfhub.dev/google/universal-sentence-encoder/4). The multilingual option uses a CNN which also has not token limit. More info [here](https://tfhub.dev/google/universal-sentence-encoder-multilingual/3).
