### ISSUE TITLE
[Installation Issue] Unable to install dependencies(tensorflow-text) while installing Top2Vec

### ISSUE THREAD

**Issue by Alisha1992** [ddangelov/Top2Vec#68]
I am trying to install `top2vec` but getting the following error when I do 'pip install top2vec==1.0.15'

ERROR: Could not find a version that satisfies the requirement tensorflow-text (from top2vec) (from versions: none)
ERROR: No matching distribution found for tensorflow-text (from top2vec)

I have windows 10, python 3.7, x64.

From what I understand, currently, tensorflow-text isn't available for Windows, so could you guys provide any resolution for this?

**Comment by ddangelov** [comment]
The next version will have a solution for this.

**Comment by Alisha1992** [comment]
@ddangelov Thanks for the update. Any ETA on the next version. And is there any `alternative package` which I can use for `short-text topic modeling` like Twitter data.

**Comment by ddangelov** [comment]
ETA is within a week. You could `pip install top2vec==1.0.14`. That will work.

**Comment by Alisha1992** [comment]
> ETA is within a week. You could `pip install top2vec==1.0.14`. That will work.

Thanks alot once again. I tried out  **pip install top2vec==1.0.14** both through command line and in juypter notebook, still i am getting the same error 
![Error top2vec](https://user-images.githubusercontent.com/39727112/98689530-091c9e80-2392-11eb-805c-4c19a676bec1.JPG)

**Comment by ddangelov** [comment]
My mistake `pip install top2vec==1.0.11`

**Comment by ddangelov** [comment]
Issue should be fixed, try the latest version 1.0.16.

**Comment by Alisha1992** [comment]
@ddangelov Thanks for the quick response, I was able to install the latest version provided by you. 
But while importing it(`from top2vec import Top2Vec`), I am getting the below error.

ImportError: Numba requires at least version 0.33.0 of llvmlite.
Installed version is 0.31.0.
Please update llvmlite.

**Comment by sandeshchand** [comment]
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Sandesh Chand\\anaconda3\\Lib\\site-packages\\~ensim\\corpora\\_mmreader.cp38-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

**Comment by phuclh** [comment]
@ddangelov I build with a docker but got the same error.

`docker build -t top2vec .`

```
#7 20.72 Collecting tensorflow
#7 20.75   Downloading tensorflow-2.10.0rc1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.9 kB)
#7 20.79 ERROR: Could not find a version that satisfies the requirement tensorflow-text; extra == "sentence_encoders" (from top2vec[sentence-encoders]) (from versions: none)
#7 20.79 ERROR: No matching distribution found for tensorflow-text; extra == "sentence_encoders"
```

My `requirements.txt`

```
top2vec[sentence_encoders]>=1.0.27
```

Thank you!

**Comment by phuclh** [comment]
I fixed the above error but got another one when using `pip`. The new issue is same as this one https://github.com/ddangelov/Top2Vec/issues/285
