### ISSUE TITLE
Are the documents close to each other in a umap plot supposed to have the same cluster label

### ISSUE THREAD

**Issue by wmmxk** [ddangelov/Top2Vec#69]
I visualized all the documents in an 2d embedding space after I trained a Top2Vec model.

I observed datapoints of the same color are not close to each other in the plot (See below). 
![Capture](https://user-images.githubusercontent.com/10648437/98706186-8de4c980-234c-11eb-995c-5d29da43fc2b.JPG)

I searched the interpretability of [distances in a umap plot](https://github.com/lmcinnes/umap/issues/92). My understanding is that the axes are not interpretability but the relative distance are valid. So I expected to see the datapoints are close to each other in a umap plot have the same cluster membership.

I thought about this because I would like to merge topics based on the distances in the umap plot. I tried to merge topics. Still datapoints in a umap plot don't have the same color.
![Capture2](https://user-images.githubusercontent.com/10648437/98707218-c9cc5e80-234d-11eb-8ec5-fa623184072b.JPG)

**Comment by ddangelov** [comment]
Could you explain what the 'cluser label' is?

**Comment by wmmxk** [comment]
> Could you explain what the 'cluser label' is?

I mean "model.doc_top", when I say "cluster label".

**Comment by wmmxk** [comment]
Some details about how I did it:

1. get the embeddings of all the documents.
2. run umap to get 2d embedding for each document
3. get the topic id of each document.
4. run  model.hierarchical_topic_reduction(15) 
5. map the original topic id to a new id using this hierarchy_dict: 
hierarchy_dict = dict(sum([[(raw_id, i) for raw_id in mapping] for i, mapping in enumerate(hierarchy)], []))

**Comment by ddangelov** [comment]
You can use `model.doc_top` for the original topic labels and `model.doc_top_redcued` for the reduced topic labels. Visualization in 2D will warp things and you should not expect all topic labels to be nearby, especially for the reduced topic labels.

**Comment by wmmxk** [comment]
> You can use `model.doc_top` for the original topic labels and `model.doc_top_reduced` for the reduced topic labels. Visualization in 2D will warp things and you should not expect all topic labels to be nearby, especially for the reduced topic labels.

I agree with you that visualization in 2d warp things to some extent. I am not expecting all the topic labels to be nearby. I thought datapoints close to each other should have same topic ids, rather than documents of the same topic scatter across the plot. Here is an example of visualizing the MINST datasets. 
![Capture](https://user-images.githubusercontent.com/10648437/98710428-a1defa00-2351-11eb-94c5-f5230965c846.JPG)

**Comment by ddangelov** [comment]
Data points that are close to each-other will share the same topic and they will not be scattered across the plot. Your plot doesn't properly show the differences in colours, so you are assuming clusters with similar shades belong to the same topic and they probably do not. I would suggest manual exploration of your data.
