### ISSUE TITLE
you must first build vocabulary before training the model

### ISSUE THREAD

**Issue by wushixian** [ddangelov/Top2Vec#7]
When I sent a list of string into Top2vec,  I get such a message.
What's the reason that causes the problem? 
Is it because the corpus is too small, or I should change the min_count of word2vec?
or I must call model.build_vocab by hand?
Thanks!

**Comment by ddangelov** [comment]
Yes this is  because your corpus is too small. 

min_count is currently defaults to 50, there will be an option to change that in the next release.

Try a larger corpus.

**Comment by wushixian** [comment]
OK，I will try large corpus. thanks.
