### ISSUE TITLE
Top2Vec(input_docs, embedding_model='universal-sentence-encoder') not working

### ISSUE THREAD

**Issue by satya-tsky** [ddangelov/Top2Vec#72]
When I run this:
```
model = Top2Vec(input_docs, embedding_model='universal-sentence-encoder')
```

I get the following error:
```
2020-11-13 13:33:07,268 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
2020-11-13 13:33:12,138 - top2vec - INFO - Downloading universal-sentence-encoder model
INFO:top2vec:Downloading universal-sentence-encoder model
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-43-6d52486e6460> in <module>
      1 # Create Top2Vec model
----> 2 model = Top2Vec(input_docs, embedding_model='universal-sentence-encoder')

~/opt/anaconda3/envs/main/lib/python3.7/site-packages/top2vec/Top2Vec.py in __init__(self, documents, min_count, embedding_model, embedding_model_path, speed, use_corpus_file, document_ids, keep_documents, workers, tokenizer, verbose)
    298         else:
    299             topic_sizes = pd.Series(self.doc_top).value_counts()
--> 300 
    301         return topic_sizes
    302 

~/opt/anaconda3/envs/main/lib/python3.7/site-packages/top2vec/Top2Vec.py in _check_model_status(self)
    647         if self.documents is not None:
    648             self.documents = np.delete(self.documents, doc_indexes, 0)
--> 649 
    650         # delete document ids
    651         if self.document_ids is not None:

~/opt/anaconda3/envs/main/lib/python3.7/site-packages/tensorflow_hub/module_v2.py in load(handle, tags, options)
    104         module_path, tags=tags, options=options)
    105   else:
--> 106     obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
    107   obj._is_hub_module_v1 = is_hub_module_v1  # pylint: disable=protected-access
    108   return obj

~/opt/anaconda3/envs/main/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in load(export_dir, tags, options)

~/opt/anaconda3/envs/main/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in load_internal(export_dir, tags, options, loader_cls)

~/opt/anaconda3/envs/main/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py in parse_saved_model_with_debug_info(export_dir)

~/opt/anaconda3/envs/main/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py in parse_saved_model(export_dir)

OSError: SavedModel file does not exist at: /var/folders/6j/5qg6z9ps6334f6v9z0tg7s6r0000gp/T/tfhub_modules/063d866c06683311b44b4992fd46003be952409c/{saved_model.pbtxt|saved_model.pb}
```

This error never came before and everything was working fine.
I downgraded to 1.0.11 and tried and still getting the same error.
Funny how it's not working now.

**Comment by ddangelov** [comment]
This is a tensorflow issue, restarting your computer should fix it. Alternatively you can download the model from https://tfhub.dev/google/universal-sentence-encoder/4 and pass it to the model:

 `model = Top2Vec(input_docs, embedding_model='universal-sentence-encoder', model_path='path/to/model')` 

More info here: https://top2vec.readthedocs.io/en/latest/api.html

**Comment by satya-tsky** [comment]
Ok,
This error doesn't come when I use distiluse-base pertained model.
When I run:
```
model = Top2Vec(input_docs, embedding_model='distiluse-base-multilingual-cased')
```
The model gets download and trained.

Something seems off about "universal-sentence-encoder" model.
Might be something to do with it's download link

**Comment by satya-tsky** [comment]
This works for me.
The argument is "embedding_model_path" and the path is the folder name containing the saved_model.pb file.
Path should not be inclusive of saved_model.pb/any .pb file. Code searches for saved_model.pb in the folder path given 
```
model = Top2Vec(input_docs, embedding_model='universal-sentence-encoder', embedding_model_path='/Users/satyarajadasara/Downloads/universal-sentence-encoder_4/')
```

**Comment by Rmsharks4** [comment]
> This works for me.
> The argument is "embedding_model_path" and the path is the folder name containing the saved_model.pb file.
> Path should not be inclusive of saved_model.pb/any .pb file. Code searches for saved_model.pb in the folder path given
> 
> ```
> model = Top2Vec(input_docs, embedding_model='universal-sentence-encoder', embedding_model_path='/Users/satyarajadasara/Downloads/universal-sentence-encoder_4/')
> ```

Hi! Even this solution is not working for me. I did exactly this!

**Comment by kunal-bhadra** [comment]
I had the same issue, and installing all the required dependencies solved it for me `top2vec[sentence_encoders] top2vec[sentence_transformers] top2vec[indexing]`

**Comment by ayyaz-azeem** [comment]
how to run this command in colab... 
i am getting ImportError: universal-sentence-encoder is not available., 
i have done following steps
pip install top2vec[sentence_encoders]
pip install tensorflow tensorflow_hub tensorflow_text
how to resolve this importerror: 
note: above mentioned embedding_model='distiluse-base-multilingual-cased' ran successfully, in colab, but how to run the universal-sentence-encoder in colab
