### ISSUE TITLE
resume training for more epochs

### ISSUE THREAD

**Issue by wmmxk** [ddangelov/Top2Vec#73]
I was training a Top2vec model on a corpus of 166,992 100-word documents (I used Doc2vec as the core of Top2Vec). 

I trained two models, one by 250 epochs and the other by 350 epochs. I found 350 epochs returned a better-separated clusters. So I would like to train more epochs. I was wondering whether it is possible for me to resume my training from a saved model.

**Comment by ddangelov** [comment]
There is no way to currently to continue training with Doc2Vec. The only thing you can do is change the `speed` when initially training, with `fast-learn` and `learn` it will train for 40 epochs, with `deep-learn` it will train for 400 epochs.
