### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by Alisha1992** [ddangelov/Top2Vec#76]
This is the code I used to train the model  on negative sentiments and the number of negative records that i had in my data is 262. 
Upon executing this line of code:
**model_neg=Top2Vec(documents=Negative_senti_data1['Mention_Text'], speed = "learn", workers=100)**

I am getting this following error:
**ValueError: need at least one array to concatenate**

**Please Note: At times, while running the above line of code, it works fine and at times, it fails.** 

So, could you please help me sort out this issue ASAP?? And also, please let me know if there is any minimum threshold for the data size??

**Comment by ddangelov** [comment]
A dataset of 262 documents is too small. For best results it's good to have at least thousands of documents.
