### ISSUE TITLE
ValueError: list.remove(x): x not in list in model.hierarchical_topic_reduction()

### ISSUE THREAD

**Issue by p-dre** [ddangelov/Top2Vec#79]
I created a model with 

```
model= Top2Vec(documents_text2, min_count = 4,
                       speed = "fast-learn", 
                       document_ids=document_ids2, 
                       workers = workers_n,keep_documents=False)
```

Then I tried to reduce the number of topics with

`model.hierarchical_topic_reduction()
`

and get this error

```
model10 = model.hierarchical_topic_reduction(1000)
Traceback (most recent call last):

  File "<ipython-input-12-4ee6e263e4a0>", line 1, in <module>
    model10 = model.hierarchical_topic_reduction(1000)

  File "C:\Users\anaconda\.conda\envs\top2vec_final\lib\site-packages\top2vec\Top2Vec.py", line 1215, in hierarchical_topic_reduction
    ix_keep.remove(most_sim)

ValueError: list.remove(x): x not in list
```

**Comment by ddangelov** [comment]
How many topics are originally in the model before the reduction to 1000? 
Did you add/delete documents from model after training and before topic reduction? 
Does this happen for other sizes of reduction other than 1000?

**Comment by p-dre** [comment]
Originally the model calculated 19906 topics. The same error occurs if I try to reduce to 19905  or  10 Topics. 

I did not delete or add documents. But I saved and loaded the model with model.save and model.load

**Comment by ddangelov** [comment]
I think I have found the error. It will be fixed in the next version, coming within the next week.

**Comment by ddangelov** [comment]
Which version of Top2Vec do you have installed?

**Comment by p-dre** [comment]
I use the Version: 1.0.16

**Comment by ddangelov** [comment]
I am not able to replicate the error. 

Could you run the following with the same `model`:

```python

top_vecs = model.topic_vectors
sizes = model.topic_sizes
smallest = sizes.sort_values(ascending=True).index[0]
res = np.inner(top_vecs[smallest], top_vecs)
most_sim = np.flip(np.argsort(res))[1]

```

What are the values of `most_sim` and `smallest` after running the above?

**Comment by MackieBlackburn** [comment]
Could it be that most_sim == smallest because two topics have a similarity of 1, so somehow "smallest" ends up in index 1 of flip(res)? In that case the topic would already be removed by line 1214. I am in the process of verifying this but I am only getting this error when the number of topics is very large and that takes a long time to run.

**Comment by ddangelov** [comment]
Yes that is exactly what I want to verify.

I think I may have found what could be causing the error. There is a topic deduplication step where topic vectors which are too similar are combined. I found that the code was missing normalization for the combined vectors, which could be causing this issue in large datasets.

**Comment by p-dre** [comment]
First I load the model an tested the reducing again. 
Same error

```
model = Top2Vec.load("Top2vec_model")

test = model.hierarchical_topic_reduction(200)
Traceback (most recent call last):

  File "<ipython-input-37-4e020d4f68c8>", line 1, in <module>
    test = model.hierarchical_topic_reduction(200)

  File "C:\Users\anaconda\.conda\envs\top2vec_final\lib\site-packages\top2vec\Top2Vec.py", line 1215, in hierarchical_topic_reduction
    ix_keep.remove(most_sim)

ValueError: list.remove(x): x not in list
```

After that I run:

```
top_vecs = model.topic_vectors
sizes = model.topic_sizes
smallest = sizes.sort_values(ascending=True).index[0]
res = np.inner(top_vecs[smallest], top_vecs)
most_sim = np.flip(np.argsort(res))[1]

most_sim
Out[43]: 57

smallest
Out[44]: 19904
```

**Comment by ddangelov** [comment]
The new version `pip install top2vec==1.0.17` has code that should prevent this error.
