### ISSUE TITLE
ImportError: universal-sentence-encoder-multilingual is not available.

### ISSUE THREAD

**Issue by njuljw76** [ddangelov/Top2Vec#82]
Hi,
 Thanks for your paper and codes, but i can't run when 'embedding_model=universal-sentence-encoder-multilingual', Error such as:

`ImportError: universal-sentence-encoder-multilingual is not available.

Try: pip install top2vec[sentence_encoders]

Alternatively try: pip install tensorflow tensorflow_hub tensorflow_text`

but I have install those successfully:

`Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /app/anaconda3/envs/bert/lib/python3.6/site-packages (from boto3->smart-open>=1.7.0->gensim->top2vec[sentence_encoders]) (0.9.4)
Requirement already satisfied: docutils<0.16,>=0.10 in /app/anaconda3/envs/bert/lib/python3.6/site-packages (from botocore<1.13.0,>=1.12.210->boto3->smart-open>=1.7.0->gensim->top2vec[sentence_encoders]) (0.15.2)`
and
`(bert) [pgrad@mgt Top2vec]$ pip install tensorflow tensorflow_hub tensorflow_text
Requirement already satisfied: tensorflow in /app/anaconda3/envs/bert/lib/python3.6/site-packages (1.12.0)
Requirement already satisfied: tensorflow_hub in /app/anaconda3/envs/bert/lib/python3.6/site-packages (0.10.0)
Requirement already satisfied: tensorflow_text in /app/anaconda3/envs/bert/lib/python3.6/site-packages (2.3.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /app/anaconda3/envs/bert/lib/python3.6/site-packages (from tensorflow) (1.0.5)
`
so may i ask you what's wrong with me? thank you very much~~Best wishes

**Comment by ddangelov** [comment]
Can you try this in the same environment? To see if you get any import errors. 

```python
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text
```

**Comment by njuljw76** [comment]
Thanks for your feedback!
I  just tried it, and found the problem with  my tensorflow's version, it's need 1.15.0~~I'm making adjustments
thank you very much!
