### ISSUE TITLE
Loaded model (from file) cannot be used to generate word embeddings

### ISSUE THREAD

**Issue by sanchez5674** [ddangelov/Top2Vec#85]
Hi Dimo, 

First of all, thanks a lot for your responsiveness. 

I can now train a model in both English and French using the multilingual sentence encoder. Once the model is trained, I can call the "embed" method to deal with my out of vocabulary words which is great. However, after I save the model to a file and reload it, the "embed" method returns a NonType so it does not work. What am I missing? It does not seem practical to have to train the model each time. 

Thanks a lot for your help!

Carlos

**Comment by ddangelov** [comment]
Hi Carlos,

If you were to call `add_documents` the embed method will load the multilingual sentence encoder. It is not saved to keep the model size to a minimum. Essentially it is only loaded when needed. 

For the time being you could solve that by calling `_check_model_status`, which should load the model. 

Cheers,

Dimo
