### ISSUE TITLE
Deterministic behavior?

### ISSUE THREAD

**Issue by tploetz** [ddangelov/Top2Vec#86]
Hi,

Really interesting paper and great that you are sharing the code. Much appreciated!

I am plying around with the code a bit and am seemingly running into some non-deterministic behavior, which I would like to hear your thoughts on.

I have a relatively small corpus of documents (3000, each with some 30 sentences; some documents may be duplicated or at least partially overlap).

I noticed that when running top2vec (no matter which encoder I am using; basically following the tutorial) multiple times, I get ever so slightly different results. That means, that the behavior of top2vec does not seem to be deterministic.

What would be the reason for this non-determinism and is there a way to make the behavior deterministic? I would need the same output every time I run the model on the same data.

Thanks!

**Comment by ddangelov** [comment]
If you are using `doc2vec` as the `embedding_model` than that will not be deterministic since training the neural network is stochastic. Additionally UMAP is also a stochastic algorithm and it is at the heart of Top2Vec. There are no plans at the moment for trying to make it deterministic.

**Comment by tploetz** [comment]
So, I am using the universal-sentence-encoder and thus the doc2vec randomness should not apply here, which only (?) leaves the UMAP stochasticity. Digging a bit deeper into the UMAP documentation, it seems like it is possible to set a random seed for it: 

https://umap-learn.readthedocs.io/en/latest/reproducibility.html  
--> map.UMAP(random_state=42).fit(data)

Any chance you could give access to this through the top2vec API?

Thanks!

**Comment by ddangelov** [comment]
Thank you pull request offer and for the research and suggestions. However it is not a priority at the moment to have it deterministic but perhaps it will be re-visited in the future.
