### ISSUE TITLE
 an invalid embedding model.

### ISSUE THREAD

**Issue by nassera2014** [ddangelov/Top2Vec#89]
Thank you for your response , i tried your proposed code (Top2Vec), when i run the programme :
model = Top2Vec(documents=arText, embedding_model="aubmindlab/bert-base-arabertv01") 
print('num topics : ',model.get_num_topics()) 
print('topics :',model.get_topics())

i get this error :
```
top2vec/Top2Vec.py", line 326, in __init__
    raise ValueError(f"{embedding_model} is an invalid embedding model.")
ValueError: aubmindlab/bert-base-arabertv01 is an invalid embedding model.
```

Thank you

**Comment by ddangelov** [comment]
Please have a look at the [Top2Vec API](https://top2vec.readthedocs.io/en/latest/api.html) for valid `embedding_model` options.
