### ISSUE TITLE
Error: 'module umap has no attribute UMAP'

### ISSUE THREAD

**Issue by lrsppp** [ddangelov/Top2Vec#9]
I encountered this error when trying to fit the model. It was fixed by [1]. Replace
`import umap`
with
`import umap.umap_ as umap`

[1] https://stackoverflow.com/questions/57242208/how-to-resolve-the-error-module-umap-has-no-attribute-umap-i-tried-installi

**Comment by ddangelov** [comment]
This issue may have been caused due to an installation error for UMAP for version 1.0.9 of Top2Vec. I have just made a fix that should prevent that from occurring, a new version is avialble on PyPl. Another fix could be `pip install umap-learn`.
