### ISSUE TITLE
Arguments for n_neighbors, n_components,  and min_cluster_size

### ISSUE THREAD

**Issue by piinghel** [ddangelov/Top2Vec#90]
Thanks for the great library!

Would it be possible to add functionality so we can choose  n_neighbors, n_components,  and min_cluster_size in the umap and hdbscan ourselves? I would like to experiment a bit myself with these values.

Thanks again!

Pieter-Jan

**Comment by doodyology** [comment]
+1

I have modified the HDBSCAN values manually, and have obtained much more manageable results. For example, on large datasets, the HDBSCAN value of 15 will find hundreds, sometimes thousands, of topics. By increasing the minimum cluster size for HDBSCAN, I have gotten around this problem.

But I'd love to have the parameters be accessible from within the API itself.

**Comment by amaleelhamri** [comment]
+1

On a dataset of 400k texts and the current parameters given to HDBSCAN, I get 1700+ topics. It would be nice to be able to update those parameters indeed.

**Comment by ddangelov** [comment]
These are now added in Top2Vec 1.0.21.
