### ISSUE TITLE
Kernal Died when using pre-trained model

### ISSUE THREAD

**Issue by pc51910** [ddangelov/Top2Vec#92]
Hi! Whenever I tried to use the pre-trained model (universal-sentence-encoder), my kernal would die after showing "INFO:top2vec:Creating lower dimension embedding of documents". This would happen both in my own windows desktop and on Google colab. The model runs well if using the default options. I'm wondering if there would be a reason. Thanks!

**Comment by ddangelov** [comment]
It sounds like you might be short on RAM or something odd is happening with UMAP. Is this a large dataset?

**Comment by ddangelov** [comment]
You need `umap-learn`. The `universal-sentence-encoder` embeddings are 512 dimensions whereas using `doc2vec` the embeddings will be 300 dimensions which would require less RAM.
