### ISSUE TITLE
Document ids

### ISSUE THREAD

**Issue by argideritzalpea** [ddangelov/Top2Vec#94]
I have passed in a list of documents to Top2Vec from a Pandas Df that has a lot of metadata. However, the document list output of Top2Vec outputs fewer documents than I had in the original object passed as input. Even though I passed in IDs as an argument to Top2Vec, it is not clear how to retrieve the original index so that I can recombine the inferred topics of the output topic list to the original dataframe that contains the document metadata.

**Comment by ddangelov** [comment]
Can you provide more details which parameters were used for training the model?

`model.document_ids` will give you the document IDs and `model.documents` will give you the documents.

**Comment by argideritzalpea** [comment]
`model.document_ids` and `model.documents` match the length of the original vector passed into `Top2Vec()`, but `model.doc_top` has fewer items and there doesn't seem to be a way to recover the original index of these inferred topics.

**Comment by ddangelov** [comment]
Which version of Top2Vec are you using? Try setting `use_corpus_file` to False.

**Comment by argideritzalpea** [comment]
Thanks, setting `use_corpus_file=False` seems to have fixed it. I was using 1.0.10. I'll update and test to see if a version change helps also.

**Comment by ddangelov** [comment]
That was an issue in that version and was fixed in 1.0.11, so using the latest should work.
