### ISSUE TITLE
'Top2Vec' object has no attribute 'documents_indexed'

### ISSUE THREAD

**Issue by sanchez5674** [ddangelov/Top2Vec#95]
Hi, 

I'm getting this error when I try to load the save Top2Vec model from a file. I'm using version 1.0.19 and I even regenerated the file in case there was some weird compatibility issue. 

Carlos

**Comment by ddangelov** [comment]
If you trained the model with the latest version, 1.0.19, you should not get this error. If you trained with an older version and trying to load with the latest you might get this error.

**Comment by sanchez5674** [comment]
Hi, 

You are correct. I reran all of my code making sure the latest version was used and the error disappeared. I must have gotten the model names confused when I ran earlier. Thanks. 

Carlos
