### ISSUE TITLE
Bug when adding new documents

### ISSUE THREAD

**Issue by YahyaL** [ddangelov/Top2Vec#96]
Hi, thanks for your amazing work.

I trained a doc2vec model. I am using my own document ids. The results are very good.

However, when I try to add new documents, I get the following error message : 
![image](https://user-images.githubusercontent.com/13187640/102131861-d64a4800-3e20-11eb-9590-031ed8fa4e51.png)

I tried it multiple times with the doc2vec model and it's still not working. I checked the gensim documentation and the argument epochs is there in the function infer_vector(). I don't understand...

I have the latest version of top2vec (1.0.19). Do you experience the same bug ?

**Comment by ddangelov** [comment]
What version of gensim do you have?

**Comment by YahyaL** [comment]
3.4.0

**Comment by ddangelov** [comment]
Try upgrading to the latest, gensim 3.8.3.

**Comment by YahyaL** [comment]
Yess it's working. Thanks so much. I love your work !!
